### ISSUE TITLE
http-flv pull failed

### ISSUE THREAD

**Issue by peterjerry** [winshining/nginx-http-flv-module#1]
http-flv pull failed. config as follows:

_http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;

    keepalive_timeout  65;

    server {
        listen       80;

        location / { 
            root   /var/www;
            index  index.html index.htm;
        } 
         
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
        
        location /live {
            flv_live on;
            chunked  on;
        }
    }
}   
    
rtmp_auto_push on;
rtmp_auto_push_reconnect 1s;
rtmp_socket_dir /tmp;

rtmp {
    out_queue   4096;
    out_cork    8;
    max_streams 64;

    server {
        listen 1935;

        application myapp {
            live on;
            gop_cache on;

            pull rtmp://live.hkstv.hk.lxdns.com/live/hks;

            on_play http://127.0.0.1:8080/on_play;
            #record all;
            #record_path /tmp;
            #record_suffix -%d-%b-%y-%T.flv;
        }
    }
}_

**Comment by winshining** [comment]
@peterjerry Well done! I will check it.

**Comment by winshining** [comment]
@peterjerry Hello, the bug was fixed, you can update to the latest code on the master branch. Thanks for your testing.

**Comment by peterjerry** [comment]
OK, thanks

**Comment by peterjerry** [comment]
http-flv pull is efficient, but video decode failed, audio decoded  normally. rtmp://live.hkstv.hk.lxdns.com/live/hks is ok , my player is flash player, config as follows:
---------------------------------------------------------
server {
    
    listen 1935;

    application myapp {
        live on;
        gop_cache on;

        pull rtmp://live.hkstv.hk.lxdns.com/live/hks;
    }
}
------------------------------------------------------------

**Comment by winshining** [comment]
@peterjerry OK. I've found the problem. There is something wrong with video analysis but I have no idea to fix it now.

**Comment by winshining** [comment]
@peterjerry Video decoding done!
