### ISSUE TITLE
请问

### ISSUE THREAD

**Issue by DahengZhang** [winshining/nginx-http-flv-module#10]
[基于nginx-rtmp-module模块实现的基于HTTP协议的FLV直播模块（nginx-http-flv-module）](http://blog.csdn.net/winshining/article/details/74910586)
请问这篇文章是您写的嘛

**Comment by winshining** [comment]
是的

**Comment by DahengZhang** [comment]
有没有讨论群组一类的呢

**Comment by winshining** [comment]
没有

**Comment by winshining** [comment]
刚建了个Q群：711969608，有问题可以加群详聊
