### ISSUE TITLE
stat page no info

### ISSUE THREAD

**Issue by lystormenvoy** [winshining/nginx-http-flv-module#101]
When I visit stat page(http://ip:port/stat)
I just can see
> Generated by nginx-rtmp-module , nginx , pid , built  

But not the publish status

My nginx.conf
````
location /stat {
            rtmp_stat all;
            rtmp_stat_stylesheet stat.xsl;
        }
        location /stat.xsl {
            root /usr/local/nginx/html;
        }
````

**Comment by winshining** [comment]
Did you use the stat.xsl in this project? Its footer is like this:

    Generated by nginx-http-flv-module 1.2.6, nginx 1.13.10, pid 27762, built Apr 10 2019 00:57:50 gcc 4.9.2 (Debian 4.9.2-10) 

If so, refresh your browser or clear the browser cache.

**Comment by misland** [comment]
> Did you use the stat.xsl in this project? Its footer is like this:
> 
> ```
> Generated by nginx-http-flv-module 1.2.6, nginx 1.13.10, pid 27762, built Apr 10 2019 00:57:50 gcc 4.9.2 (Debian 4.9.2-10) 
> ```
> 
> If so, refresh your browser or clear the browser cache.

yes!!solve the problem after refresh the page:)
