### ISSUE TITLE
Nginx不定时失去响应

### ISSUE THREAD

**Issue by lystormenvoy** [winshining/nginx-http-flv-module#102]
主要在用点播服务，可能与点播有关，导致无响应
点播的MP4文件有2.6GB，长度03:46:23
top里面看到work process 使用了100% CPU
error和access日志不再打印
stat页面无法访问
无法往nginx推流
使用`perf top -p 8560` 可以看到

````
76.06%  nginx     [.] ngx_rtmp_mp4_parse
  23.70%  nginx     [.] ngx_rtmp_mp4_parse_trak
````

**Comment by winshining** [comment]
点播部分代码我没有改过，请用nginx-rtmp-module对比测试

**Comment by lystormenvoy** [comment]
> 点播部分代码我没有改过，请用nginx-rtmp-module对比测试

好的，原本我是用rtmp module的，也是有这个问题，后来想换http flv试试，结果也一样

**Comment by winshining** [comment]
OK，那你给arut发个issue吧，说不定他会发现一些问题
