### ISSUE TITLE
从url传递自定义参数到exec_pull

### ISSUE THREAD

**Issue by liangtaikonaut** [winshining/nginx-http-flv-module#104]
Winshining, 你好！

希望传递自定义参数到exec_pull，譬如：
http://www.mystreamserver.com/live?app=downstream&stream=record-20190524103000&mymultiaddr=225.0.0.1:5000
$app和$stream用于ffmpeg对录像转码并在网页回看，$mymultiaddr=225.0.0.1:5000，是自定义的参数，用于ffmpeg把录像通过组播方式输出给专用设备或软件。
可能还有其它一些自定义参数的要求。

请问能否实现自定义参数的传递？
或者给指明一条实现的路线。

多谢！

**Comment by winshining** [comment]
代码里已有内置参数$app和$name可以用，分别对应rtmp协议的url(rtmp://host[:port]/app/stream)中的app和stream，也就是你提到的$app和$stream。要实现自定义的参数传递，可以参考ngx_rtmp_exec_module.c的代码。
