### ISSUE TITLE
建议支持HEVC

### ISSUE THREAD

**Issue by wanstonq** [winshining/nginx-http-flv-module#105]
建议支持HEVC，可以输出HLS、Dash、Http-Flv等

**Comment by winshining** [comment]
等Adobe更新FLV规范（这个基本上没什么可能了）

**Comment by syklevin** [comment]
could take a look in this two patchs from OpenVisualCloud

[Add-hevc-support-for-rtmp-and-hls-on-Nginx-Http-Flv](https://raw.githubusercontent.com/VCDP/CDN/master/0001-Add-hevc-support-for-rtmp-and-hls-on-Nginx-Http-Flv.patch)

[add-HEVC-support-for-dash](https://raw.githubusercontent.com/VCDP/CDN/master/0002-add-HEVC-support-for-dash.patch)

**Comment by winshining** [comment]
@syklevin Thx! I won't update the project unless Adobe updates the FLV spec.
BTW, the HLS spec demands that if HEVC is used for video, container format MUST be fMP4 but not ts, see the section `General Authoring Requirements` in [HTTP Live Streaming](https://developer.apple.com/documentation/http_live_streaming/hls_authoring_specification_for_apple_devices) for details.
