### ISSUE TITLE
當ffmpeg 推流按 q 停止, 再次推流時, 播放端不會接著播放

### ISSUE THREAD

**Issue by maverick061** [winshining/nginx-http-flv-module#106]
在本地測試推流 (raspberry pi3b+)
ffmpeg -f video4linux2 -i /dev/video0 -vcodec h264_omx -zerocopy 1 -b:v 400k -s 640x480 -acodec libfaac -b:a 64k -pix_fmt yuv420p  -g 30 -f flv rtmp://192.168.168.200/rtmp/live2

播放端
win7
fflags nobuffer rtmp://192.168.168.200/rtmp/live2

當推流按 q 結束推流, 播放端畫面會停格,但不關閉, 稍後同樣的設定繼續推流則播放端並不會接著播放必需重新連接, 這個問題在原來的 rtmp-module 不會產生, 使用原來的 rtmp-module 當繼續推流則客戶端會很快的接著播放不需要關閉重新連接.

**Comment by winshining** [comment]
已修改为与nginx-rtmp-module保持一致，请使用最新的代码测试。

**Comment by maverick061** [comment]
hi @winshining .

大神實在太牛了..測過沒這問題了, 感謝您.

**Comment by maverick061** [comment]
hi @winshining 

不好意思再來麻煩您, 目前是會接著繼續播放了, 可是中斷播放前原本差距都在 1秒內, 現在重新推送後播放端繼續播放會有約 2 秒的差距, 請問這有辦法處理嗎??

**Comment by winshining** [comment]
@maverick061 可以把gop_cache关了，否则每次都会延迟一个GOP，不过关了之后首屏时间就长了。

**Comment by maverick061** [comment]
我測試的結果好像和 gop_cache  沒很大關係, 我測 gop_cache on or off , 只要發現差距大於1秒了,推流馬上關閉再開,則播放端又能追上了...奇怪的問題...
