### ISSUE TITLE
关于http2.0的支持

### ISSUE THREAD

**Issue by SongLin123** [winshining/nginx-http-flv-module#110]
你好，从我个人的尝试和issues的讨论里发现http2应该是还没有支持的。
我现在的需求是有超过6个的并发播放数的，因为浏览器的[同源连接数不能超过6个的限制](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Connection_management_in_HTTP_1.x)，
只能用域名分片来实现，但是这样对客户端的代码就不太友好了。
http2.0没有这个限制，现在有对http2支持的计划么？

**Comment by winshining** [comment]
你的问题与 #33 差不多，目前没有支持http2的计划。
我去年大概浏览过Nginx中相关的源代码，Nginx是在HTTP模块的header_filter函数链表中处理http2的回复（并且只处理HTTP header，没有处理HTTP body的函数）。
nginx-http-flv-module本身发送HTTP-FLV回复的函数并没有调用Nginx提供的HTTP回复接口，现有的发送HTTP回复的header函数是从ngx_http_header_filter_module.c中拆出来的，body部分直接调用了send函数，所以并不会去调用http2的header_filter函数。如果要完全调用Nginx提供的接口，我评估过，牵涉的范围有点大，为了稳定，暂时不会修改。
