### ISSUE TITLE
配置文件的问题

### ISSUE THREAD

**Issue by gy2331314** [winshining/nginx-http-flv-module#113]
wiki上的默认配置文件中，rtmp_auto_push on;是打开的，不同worker进程都会向上游发起pull，这种增加带宽消耗的做法并不合适，我想测试下您这个模块的pull同名回源合并，请问rtmp_auto_push on;这个配置仍要打开吗？

**Comment by winshining** [comment]
此模块不支持pull同源合并，rtmp_auto_push只是在多进程模式下让一个进程接收到推流后relay到其他进程，跟pull没关系。
