### ISSUE TITLE
master版本多个客户端同时拉http-flv流时，如果有新的客户端播放，那么之前正在播放的客户端就会卡住

### ISSUE THREAD

**Issue by qinweiWill** [winshining/nginx-http-flv-module#115]
When you meet a bug, please open the issue including a title prefixed by '[bug]' and describe it as follows:

### Expected behavior
可以支持多个客户端同时拉http-flv流

### Actual behavior
master版本多个客户端同时拉http-flv流时，如果有新的客户端播放，那么之前正在播放的客户端就会卡住

### Steps to reproduce the behavior 
1、往nginx推rtmp流  2、使用多个vlc同时播放http-flv流

**Comment by qinweiWill** [comment]
这个是我的nginx.conf的关键配置：
worker_processes  1;
events {
    worker_connections  1024;
}
http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    server {
        listen 8088;
        location /live {
            flv_live on;
            chunked_transfer_encoding on; #支持'Transfer-Encoding: chunked'方式回复
        }
    }
}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;
        application live {
            live on;
            gop_cache off;
            record off;
        }
    }
}

**Comment by winshining** [comment]
OK，我测试了一下，的确有这个问题，应该是最近修改的代码引入的bug

**Comment by qinweiWill** [comment]
我测试的时候发现好像是时间戳的问题，第二个客户端开始播放时，第一个客户端拉的视频流的视频和音频的时间戳突然又从0开始计数。

> OK，我测试了一下，的确有这个问题，应该是最近修改的代码引入的bug

**Comment by winshining** [comment]
@qinweiWill bug已经修复，请使用最新的代码测试，测试完不管问题解决与否，都请回复我一下，谢谢！

**Comment by qinweiWill** [comment]
@winshining 您好，早上在我电脑上测试了下，视频的时间戳貌似还是有点问题。先后下载3条HTTP-FLV流的视频，有两个视频的时间戳从0开始，但是中间突然往前跳了大约10s左右。还有一个视频的时间戳不是从0开始。
使用video.js播放时，后面播放的视频还是会概率性的影响前面的视频（不像之前必现）。

**Comment by winshining** [comment]
@qinweiWill 这次修改后，我在Linux和Windows都测试过了，使用VLC和flv.js都已经没有问题，测试完后请给我回复，如果修复了，请帮我点赞（修复这个bug花了好多时间，哈哈），谢谢反馈bug！

**Comment by qinweiWill** [comment]
@winshining 您好，非常感谢修复bug。我今早在我电脑上测试了下，发现视频流的时间戳跳变的情况确实没有了。**但是貌似视频的时间戳仍然不是从0开始的**。

**Comment by winshining** [comment]
@qinweiWill 把chunked_transfer_encoding设置为off，时间戳就会从0开始了，为on时不是致命问题，空了我再改。
