### ISSUE TITLE
http-flv单路播放2秒后卡着

### ISSUE THREAD

**Issue by zjx94** [winshining/nginx-http-flv-module#116]
When you meet a bug, please open the issue including a title prefixed by '[bug]' and describe it as follows:

### Expected behavior
obs推流，可同时多个客户端播放http-flv
### Actual behavior
单路播放。使用video.js? 或者flv.js ,播放了1-2秒，就会卡着转圈。flv.js基本是卡着就不动了，video.js 卡了5秒之后还会继续走。
### Steps to reproduce the behavior 
obs推流，用flv.js自带demo播放http-flv地址。即使用了新版本，2019年8月14日10:50下载。

**Comment by zjx94** [comment]
这是我的nginx配置以及flv.js配置
======================
rtmp {
    server {
        listen 1936;

        application live {
            live on;
			gop_cache on;
			#wait_key on;
			#drop_idle_publisher 90s;
            #record keyframes;
            #record_path /tmp;
            #record_max_size 128K;
            #record_interval 30s;
            #record_suffix .this.is.flv;

			#notify_method get;
			#publish_notify on;
            #on_publish http://192.168.1.90:5000/post;
            #on_play http://127.0.0.1:8087/on_play;
            #on_record_done http://localhost:8080/record_done;
        }
    }
}
http {
   
    server {
        listen       8089;
        server_name  localhost;
......
		location /live {
                        flv_live on;
			#chunked_transfer_encoding  on; #open 'Transfer-Encoding: chunked' response
			#add_header 'Access-Control-Allow-Credentials' 'true'; #add additional HTTP header
			add_header 'Access-Control-Allow-Origin' '*'; #add additional HTTP header
			#add_header Access-Control-Allow-Headers X-Requested-With;
			#add_header Access-Control-Allow-Methods GET,POST,OPTIONS;
			#add_header 'Cache-Control' 'no-cache';
        }
======================
 flvjs.createPlayer(mediaDataSource, {
		enableWorker: false,
		enableStashBuffer: false,
		stashInitialSize: 128,});

**Comment by winshining** [comment]
与 #115 重复

**Comment by zjx94** [comment]
不一样吧？我单路播放都卡着，我也是看了115的，看了不一样的问题才发issue的，更新了新版本也依旧没有解决问题。

**Comment by winshining** [comment]
单路播放的间戳没有问题， 造成卡顿的原因很大可能是你配置不对，你如果清楚配置实例里写的那些参数的意义，那你可以省略，不然请按照配置实例里的参数来配置。
举个例子：造成卡顿的一个原因是默认的

    out_queue

不够大，会造成服务器丢帧，你可以按照配置实例里配置后再试试。

**Comment by zjx94** [comment]
感谢老铁的贡献和及时的回复（热泪盈眶）
我windows x64平台照实例设置
out_queue 等参数后
播放后从原来的2秒到十几秒后才会发生卡住的情况。
发现要加上
rtmp_auto_push on;
rtmp_auto_push_reconnect 1s;
rtmp_socket_dir /tmp;
单路播放才不会卡顿。(*^▽^*)
但是#115的问题好像的确还是存在，很大概率会重现。
（为啥gop cache打开后，延时起码11秒以上(ΩДΩ)  ）
