### ISSUE TITLE
开启http-flv后hls无法一起播放

### ISSUE THREAD

**Issue by zjx94** [winshining/nginx-http-flv-module#117]
When you meet a bug, please open the issue including a title prefixed by '[bug]' and describe it as follows:
（仔细看了首页，没发现不能一起使用的说明）
### Expected behavior
windows平台，本想开启http-flv与hls，一起播放。
### Actual behavior
经过多次试验，当把http-flv关闭后（ /live 下的配置注释后），hls可以播放，但是当把http-flv打开（配置注释打开后），只能播放http-flv,hls无法播放。
error.log里显示
2019/08/15 16:41:44 [error] 12264#13356: *3 flv live: app args MUST be specified, client: 192.168.1.65, server: localhost, request: "GET /live/test.m3u8 HTTP/1.1", host: "192.168.1.204:8089"
(感觉是flv来处理了这个hls的地址)
### Steps to reproduce the behavior 
注释的就是这四句话
后面配上nginx配置。
           # flv_live on;
           # chunked_transfer_encoding  off; #open 'Transfer-Encoding: chunked' response
           # add_header 'Access-Control-Allow-Credentials' 'true'; #add additional HTTP header
           # add_header 'Access-Control-Allow-Origin' '*'; #add additional HTTP header

**Comment by zjx94** [comment]
`
#user  nobody;
worker_processes  1;

error_log  logs/error.log notice;
#debug_log  logs/debug.log debug;
#info_log  logs/info.log info;
#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}
rtmp_auto_push on;
rtmp_auto_push_reconnect 1s;
rtmp_socket_dir ./tmp;
rtmp {
	out_queue           4096;
    out_cork            8;
    max_streams         128;
    timeout             15s;
    drop_idle_publisher 15s;
	log_interval 5s; #interval used by log module to log in access.log, it is very useful for debug
    log_size     1m; #buffer size used by log module to log in access.log
    server {
        listen 1935;

        application live {
            live on;
			#hls on;
			#hls_nested on;
			#hls_path ./html/live;
			#hls_fragment 1s;
			#hls_max_fragment 2s;
			#hls_playlist_length 60s;
			gop_cache on;
			#wait_key on;
			#drop_idle_publisher 90s;
            #record keyframes;
            #record_path /tmp;
            #record_max_size 128K;
            #record_interval 30s;
            #record_suffix .this.is.flv;

			#notify_method get;
			#publish_notify on;
            #on_publish http://192.168.1.90:5000/on_publish;
            #on_play http://192.168.1.90:5000/on_play;
            #on_record_done http://localhost:8080/record_done;
        }
		application hls {
            live on;
            hls on;
            hls_path ./html/live;
        }
    }
}
http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       8089;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   ./html;
            index  index.html index.htm;
        }
		location /stat {
            rtmp_stat all;
            rtmp_stat_stylesheet stat.xsl;
        }
        location /stat.xsl {
            root html;
        }
		location /live {
            flv_live on;
			chunked_transfer_encoding  off; #open 'Transfer-Encoding: chunked' response
			add_header 'Access-Control-Allow-Credentials' 'true'; #add additional HTTP header
			add_header 'Access-Control-Allow-Origin' '*'; #add additional HTTP header
			 
        }
		# http播放地址
        location /hls {
			types {
			 application/vnd.apple.mpegurl m3u8;
			 video/mp2t ts;
			}
			root ./html;        #hls文件路径
			add_header Cache-Control no-cache;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        } 
    }
 
}
`

**Comment by winshining** [comment]
Nginx的匹配问题，你可以自己修改源代码支持
