### ISSUE TITLE
使用dso_tool编译成动态模块加载后NGINX不断重启进程

### ISSUE THREAD

**Issue by luoshuijs** [winshining/nginx-http-flv-module#118]
因为使用得是二进制安装，安装模块还得重新编译，模块太多了，重新编译很麻烦。后面知道NGINX有一些版本可以使用动态模块加载。但是昨天折磨了一下，用dso_tool命令编译成so库文件后进入nginx.conf使用dso载入
<code> 
     dso {
        load ngx_http_flv_live_module.so;
    }
</code> 
检查配置以时确认模块已经载入了，但是发现连网页都打不开，后面查看错误日记才发现NGINX的缓存管理器不断重启： 
2019/08/18 14:44:53 [alert] 1311#0: cache manager process 16243 exited on signal 11
2019/08/18 14:44:55 [alert] 1311#0: worker process 16244 exited on signal 11
2019/08/18 14:44:57 [alert] 1311#0: cache manager process 16247 exited on signal 11
2019/08/18 14:44:59 [alert] 1311#0: worker process 16250 exited on signal 11
2019/08/18 14:45:01 [alert] 1311#0: cache manager process 16256 exited on signal 11
2019/08/18 14:45:03 [alert] 1311#0: worker process 16259 exited on signal 11
2019/08/18 14:45:05 [alert] 1311#0: cache manager process 16260 exited on signal 11
2019/08/18 14:45:07 [alert] 1311#0: worker process 16261 exited on signal 11
2019/08/18 14:45:09 [alert] 1311#0: cache manager process 16264 exited on signal 11
后面懒得用IDA去调试看看是什么错误了（懒）
我使用的是：
Tengine/2.2.3 (nginx/1.8.1)
因为是二进制安装，应该不是模块冲突问题......
后面我也应该是NGINX版本问题，但是实在没其他机子测试了emmmm

**Comment by winshining** [comment]
亲，这边建议您使用Nginx呢！

**Comment by luoshuijs** [comment]
算了还是老实使用Nginx编译进去，就是怕麻烦╮(─▽─)╭
