### ISSUE TITLE
The module deployment failed to push the stream after ali cloud server

### ISSUE THREAD

**Issue by Believe-Myself** [winshining/nginx-http-flv-module#119]
I installed the Nginx module on the ali cloud server, and I could see the welcome interface in the browser, but I failed to use OBS to push the stream. What's the reason?

**Comment by winshining** [comment]
Check carefully what you did before and after you installed the module on the cloud server, for example, was port open? So many people have already been running Nginx with this module successfully on the Ali cloud server.
