### ISSUE TITLE
Does it support reply from origin server like SRS hstrs 

### ISSUE THREAD

**Issue by robinyeeh** [winshining/nginx-http-flv-module#12]
Does it support reply from origin server like SRS hstrs

**Comment by winshining** [comment]
Yes, nginx-rtmp-module supports similar feature via pull & push directive.

**Comment by robinyeeh** [comment]
May i know how can use it ?

**Comment by robinyeeh** [comment]
BTW, do you have QQ or wechat

**Comment by winshining** [comment]
You may refer to pull & push directives in nginx-rtmp-module's wiki and you can contact me via email.
