### ISSUE TITLE
[Bug] live broadcasting delay 4-5s

### ISSUE THREAD

**Issue by liuhao-121** [winshining/nginx-http-flv-module#120]
When you meet a bug, please open the issue including a title prefixed by '[bug]' and describe it as follows:

### Expected behavior
Fast broadcasting and 1-2s delay of live broadcasting

### Actual behavior
Slow broadcasting, live broadcasting delay 4-5s

### Steps to reproduce the behavior 
I just added gop_cache in the configuration; the other is basically the default configuration; the result is that HTTP flv can play, broadcast quickly, but there is a delay.

**Comment by winshining** [comment]
Firstly, I don't think it's a **BUG**:)
If the directive `gop_cache` is turned on, it decreases the time to see the first picture of streaming video, but it leads to a GOP latency. Turning it off will increase the time of arrival of the first picture of streaming video, but you get less latency.
So if you set a long time GOP (I've ever seen an 8 seconds GOP in a stream, for example) in your publisher and you turn on the directive `gop_cache`, you will get a long time latency.
If you want a low latency, you can:
1.turn off the directive `gop_cache`.
2.set a short time GOP (no less than 1 second) in your publisher with `gop_cache` on.
The following are some sample pictures I tested with `gop_cache` off (Nginx was running on a Ali cloud server and the publisher(OBS) and play(ffplay) are on my PC):
![1](https://user-images.githubusercontent.com/3250905/63487742-f3962d00-c4de-11e9-83b8-0d742d6bd4be.JPG)
+++++++++++++++++++++++++++++++++++++++++++++++++++
![2](https://user-images.githubusercontent.com/3250905/63487745-fabd3b00-c4de-11e9-8a29-4db22c20fc07.JPG)
+++++++++++++++++++++++++++++++++++++++++++++++++++
![3](https://user-images.githubusercontent.com/3250905/63487752-03157600-c4df-11e9-86db-44e14f7e402f.JPG)
