### ISSUE TITLE
ffmpeg+nginx-http-flv-module+flv.js延迟达到3s，想要延迟1s一下，求问怎么解决

### ISSUE THREAD

**Issue by github-wx-china** [winshining/nginx-http-flv-module#124]
1、现象
后端启动进程：基于ffmpeg代码实现读摄像头设备，并进行推流
前端网页显示视频：发现总是有3s左右的延迟
2、期望前端显示只有1s以下的延迟
3、问题：都是在一台笔记本上的前后端数据传输，不应该存在延迟，ffmpeg处理设备以及发送数据（其中ffmpeg编码设置的gop_size为10）的耗时在50ms，应该是nginx-http-flv-module导致的延时，但是不清楚参数哪里配置的不合理
4、配置：
```
worker_processes  1;
events {
    worker_connections  1024;
}
http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    server {
        listen           80;
        #listen [::]:80   ipv6only=on default_server;         
        server_name      localhost;
        root             /usr/local/nginx/html/;
        limit_rate_after 5m;
        limit_rate       1000k;
        index            index.html;
        charset          utf-8;
        location /live {
            flv_live on;
            chunked_transfer_encoding off;
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
            add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
            add_header Access-Control-Allow-Credentials true;
            if ($request_method = 'OPTIONS') {
                return 204;
            }
        }
        location ~ \.flv {
            flv;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}
rtmp {
    server {
        listen 1935;
        chunk_size  1024;
        application myapp {
            live on;
            gop_cache off;
        }
    }
}

```

**Comment by winshining** [comment]
延迟跟推流器，服务器和播放器都有关，我的测试环境如下：
OS：Windows 7
Publisher：OBS 21.1.2 (GOP自动)
Player：ffplay 20180226-f4709f1-win64-static
Server：Nginx-1.17.4 + nginx-http-flv-module (GitHub最新)
截图如下：
![snapshot_1](https://user-images.githubusercontent.com/3250905/64158013-5934d280-ce6a-11e9-95f0-b999572d5e98.JPG)
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
![snapshot_2](https://user-images.githubusercontent.com/3250905/64158060-6fdb2980-ce6a-11e9-8d5c-ef66f108694a.JPG)
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
![snapshot_3](https://user-images.githubusercontent.com/3250905/64158071-7669a100-ce6a-11e9-9a8d-9a19eda78d9e.JPG)
这几乎是本地推流和播放能做到的最低的延迟了，远程的之前已有截图，可以看这儿#120。
如果要求延迟在1s内，要么优化Publisher和Player，要么使用非TCP协议的服务器。
配置如下：
    worker_processes  1;
    error_log  logs/error.log  error;

    events {
        worker_connections  1024;
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;

        server {
            listen       80;
            server_name  localhost;

            location /live {
                live on; #open flv live streaming (subscribe)
                chunked_transfer_encoding on; #open 'Transfer-Encoding: chunked' response
            }

            location / {
                root   docs/html;
                index  index.html index.htm;
            }

            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   html;
            }
        }
    }

    rtmp {
        out_queue   4096;
        out_cork    16;
        max_streams 128;

        server {
            listen 1935;
            server_name localhost;

            application myapp {
                live on;
                gop_cache off; #open GOP cache for low latency
            }
        }
    }

**Comment by github-wx-china** [comment]
十分感谢，我自己再摸索摸索

**Comment by TheDawnXu** [comment]
我也是这个方案   延迟大概3s左右 有解决方案可以参考么

**Comment by onecorner** [comment]
为什么你延迟才3s，我的延迟一分多钟

**Comment by BeyondTheBlade** [comment]
目前线上延迟5秒，已经设置了gop_cache off，有没有好的办法？ @winshining @github-wuxi @
