### ISSUE TITLE
使用的静态编译，仍然出现unknown directive "flv_live"

### ISSUE THREAD

**Issue by liangmuxue** [winshining/nginx-http-flv-module#125]
操作系统 centos7.3
./configure --add-module=../nginx-http-flv-module
make 和 make install都编译通过了

配置flv_live on选项，启动后报错: unknown directive "flv_live"

**Comment by liangmuxue** [comment]
nginx version: nginx/1.12.2
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) 
built with OpenSSL 1.0.2k-fips  26 Jan 2017
TLS SNI support enabled
configure arguments: --add-module=../nginx-http-flv-module

**Comment by winshining** [comment]
看样子你用的是系统自带的Nginx。
1.下载跟系统自带的Nginx的版本相同的Nginx源代码
2.使用它的编译参数，外加动态编译nginx-http-flv-module的编译参数
3.编译
4.得到so文件后，按照README里动态加载nginx-http-flv-module的方法加载so文件
5.启动或者重启Nginx

**Comment by liangmuxue** [comment]
是这个原因，删除了系统自带的nginx，使用正常！感谢。
