### ISSUE TITLE
stunnel issue

### ISSUE THREAD

**Issue by pkquell** [winshining/nginx-http-flv-module#127]
Sending rtmps via stunnel gives the following error:
<pre><code>2019/09/22 21:45:04 [notice] 27968#0: signal process started
2019/09/22 21:45:05 [notice] 27978#0: using the "epoll" event method
2019/09/22 21:45:05 [notice] 27978#0: nginx/1.16.1
2019/09/22 21:45:05 [notice] 27978#0: built by gcc 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
2019/09/22 21:45:05 [notice] 27978#0: OS: Linux 3.10.0-957.12.1.el7.x86_64
2019/09/22 21:45:05 [notice] 27978#0: getrlimit(RLIMIT_NOFILE): 1024:4096
2019/09/22 21:45:05 [notice] 27979#0: start worker processes
2019/09/22 21:45:05 [notice] 27979#0: start worker process 27980
2019/09/22 21:45:05 [notice] 27979#0: start cache manager process 27981
2019/09/22 21:45:15 [info] 27980#0: *1 client connected '127.0.0.1'
2019/09/22 21:45:15 [error] 27980#0: *1 connect: failed to process virtual host, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 21:45:15 [info] 27980#0: *1 disconnect, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 21:45:15 [info] 27980#0: *1 deleteStream, client: 127.0.0.1, server: 0.0.0.0:1935</code></pre>

My stunnel setting:
<pre><code>sslVersion = all
TIMEOUTclose = 0

socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1

[rtmps]
accept = 0.0.0.0:8443
connect = 127.0.0.1:1935
cert = /etc/stunnel/server.crt
key = /etc/stunnel/server.key</code></pre>

No error occurs when i using [nginx-rtmp-module](https://github.com/arut/nginx-rtmp-module).

I think this is an issue with the tcUrl parsing process.

**Comment by winshining** [comment]
The client used RTMPS?

**Comment by winshining** [comment]
Sorry, I didn't notice carefully what you posted, I will check it later.
