### ISSUE TITLE
I found x-flv use large memory in a long time ..

### ISSUE THREAD

**Issue by yx601** [winshining/nginx-http-flv-module#13]
when I open flv_live , nginx use large memory in a long time(my server is 32Gb momery,it use all momery in just 6 hour). Is there have any memory leaks?

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                               
 8127 www       20   0 7227172 6.848g   1452 S   0.0 21.9   2:01.04 nginx                                                 
 8128 www       20   0 4135696 3.899g   1424 S   0.0 12.5   1:12.31 nginx

**Comment by winshining** [comment]
Then would you please tell me how to reproduce it?

**Comment by winshining** [comment]
@yx601 I had mainly tested the HTTP-FLV feature before_ you posted this issue, it had nothing to do with memory leak, while play via RTMP which I had thought to be very __stable did.

**Comment by winshining** [comment]
@yx601 I am sorry. I found how to reproduce the bug. In single child process mode, everything is OK, while in multiple child process mode with 'rtmp_auto_push' turned on, memory leak increases apparently.

**Comment by yx601** [comment]
thank you for your reply , I really like this project , I appreciate what you did.

**Comment by yx601** [comment]
@winshining yes, I have 4 child process ,and turned 'rtmp_auto_push' on . So I can't turn on the switch ?

**Comment by yx601** [comment]
@winshining when I turn off rtmp_auto_push , and set worker_processes 4, the url:"live?app=xxx&stream=xxx" is not stable . It will response 500 code sometime.

**Comment by winshining** [comment]
@yx601 Memory leak bug was fixed. I've tested it using srs-bench(RTMP, 20 clients) and vlc (HTTP-FLV, 1 client) over an hour and memory has only increased 1M. You can download the latest code to test it.
Thanks again for posting this issue.
Good luck!

**Comment by winshining** [comment]
BTW, test has been done in multiple children processes mode and with 'rtmp_auto_push' turned on.

**Comment by yx601** [comment]
@winshining thank you.I like your code,it is really good~
