### ISSUE TITLE
作者大大你好，我装完nginx-http-flv-module，ffmpeg仍然需要自己去安装是么

### ISSUE THREAD

**Issue by dorseysen** [winshining/nginx-http-flv-module#134]
如题。

**Comment by dorseysen** [comment]
我这边已经有可以用的rtmp流媒体地址，现在要在HTML5上播放，nginx-http-flv-module已经装完并且和nginx搭配编译，nginx已经正常再跑。为了方便测试，配置里的nginx写死了一串rtmp流，比如rtmp://live.hkstv.hk.lxdns.com/live/hks。那我页面上的访问如何搭配flv.js实现播放呢，就是最终的http流地址我要到哪里拿。

**Comment by dorseysen** [comment]
我这边已经有可以用的rtmp流媒体地址，现在要在HTML5上播放，nginx-http-flv-module已经装完并且和nginx搭配编译，nginx已经正常再跑。为了方便测试，配置里的nginx写死了一串rtmp流，比如rtmp://live.hkstv.hk.lxdns.com/live/hks。那我页面上的访问如何搭配flv.js实现播放呢，就是最终的http流地址我要到哪里拿。

**Comment by dorseysen** [comment]
这是我配置的测试地址
application myapp {
            live on;
            gop_cache on; #打开GOP缓存，减少首屏等待时间
            pull rtmp://live.hkstv.hk.lxdns.com/live/hks;   #直播推流测试
        }

**Comment by cyxiaozhen** [comment]
作者你好，我想问下你这个项目是做类似ffmpeg的转码还是类似srs的推流呢，还有如何在项目里配置视频流地址。
