### ISSUE TITLE
nginx-http-flv-module支持动态转化rtmp流为httpflv么？

### ISSUE THREAD

**Issue by dorseysen** [winshining/nginx-http-flv-module#136]
When you meet a bug, please open the issue including a title prefixed by '[bug]' and describe it as follows:

### Steps to reproduce the behavior 

nginx-http-flv-module支持动态转化rtmp流为httpflv么？还是说只能一个application一个静态的流地址？

**Comment by winshining** [comment]
nginx-http-flv-module是在nginx-rtmp-module基础上开发的，请参考[nginx-rtmp-module](https://github.com/arut/nginx-rtmp-module)的wiki中的[Relay](https://github.com/arut/nginx-rtmp-module/wiki/Directives#relay)一节的说明。
