### ISSUE TITLE
ckplayer直播

### ISSUE THREAD

**Issue by Believe-Myself** [winshining/nginx-http-flv-module#138]
想请教大家个问题，我用这个模块和flv.js实现直播了，但是它可以支持在ckplayer上不依赖flash直播吗？感谢！

**Comment by winshining** [comment]
最好向ckplayer官方咨询。

**Comment by Believe-Myself** [comment]
解决了，在这里跟大家分享。ckplayer使用rtmp流直播必须使用flash，较HTML播放效果确实好，延迟一秒，基本不卡顿。

**Comment by winshining** [comment]
@Believe-Myself flv.js播放的是HTTP-FLV，不需要Flash，要播放RTMP，必须要Flash Player。之前你问的误导我了，不过仍然感谢你的分享，谢谢！
