### ISSUE TITLE
你好，nginx-http-flv-module有同步的机制么？

### ISSUE THREAD

**Issue by dorseysen** [winshining/nginx-http-flv-module#139]
When you meet a bug, please open the issue including a title prefixed by '[bug]' and describe it as follows:

### Steps to reproduce the behavior 
我们遇到的具体问题是这样子的，视频在播着播着会自动断，比如播放5分钟，然后又会重新开始播那一段，我想着，那边在推流，这边的ffmpeg在拉流，会不会存在着拉着拉着一边快一边慢导致缓存不断积累的情况，最终导致崩掉。

**Comment by winshining** [comment]
Nginx如果崩溃，请贴出日志。
推流和拉流的速率如果不一样（取决于网络），nginx-http-flv-module会丢帧，如果连接（不管是推流还是拉流），长时间没有数据传输，nginx-http-flv-module默认会超时关闭连接。
