### ISSUE TITLE
推送没有声音的视频，flv不能播放

### ISSUE THREAD

**Issue by genshangjiepai** [winshining/nginx-http-flv-module#14]
When you meet a bug, please open the issue including a title prefixed by '[bug]' and describe it as follows:

**Comment by winshining** [comment]
暂时没测试播放只有视频的情况

**Comment by winshining** [comment]
刚用ffmpeg分离了一个正常视频的视频数据出来，测试没有问题，你能说说怎么重现的么？方便提供测试视频么？
