### ISSUE TITLE
seems memory leak

### ISSUE THREAD

**Issue by longxx007** [winshining/nginx-http-flv-module#140]
1.2.7 release，and nginx 1.12.2, when 1k playing pressure test, 1g has been occupied, but when all players disconnect, 1g memory are still occupied 
### Expected behavior
when players disconnect, the big memory should return to os
### Actual behavior
when players disconnect, the big memory did NOT return to os
### Steps to reproduce the behavior 
1 worker 
deamon on
push one stream
start 1000 players playing this stream
1 minute later, stop players
watch the memory

**Comment by longxx007** [comment]
![image](https://user-images.githubusercontent.com/18022894/69523020-c6ee2780-0f9d-11ea-8802-5f66f71b4b58.png)

**Comment by winshining** [comment]
Don't you know Nginx has memory pools？The memories allocted in memory pools will not be freed after being used, but put in chains. They will be cycled in the next time, this avoids allocating new memories and so improves performance.
You can test the memory leak by stopping the 1k players and initiating another 1k play requests and see memory consumption. If there is a BIG difference between two memory consumptions, please let me know.

**Comment by longxx007** [comment]
感谢您的回复，我遇到的问题其实是，长时间(一个月)跑之后，内存持续会增长，但并发并没有超过1k，可最后的内存增加到几个g以上了。
然后我做了上面一个测试，1000并发之后，大部分的内存都没有被回收。我查看代码，s->connectiong->pool的内存在结束后会被回收，s中的其他pool似乎也都会被回收(destroy)，cscf->pool不会被回收，我打开NGX_RTMP_DEBUG_POOL然后统计<server_index>0</server_index>
<pool><nlarge>58</nlarge><size>9265</size></pool>
并发时的pool我都尝试统计了，1000个client 每个client
client><pool><nlarge>3</nlarge><size>870</size></pool>
<pool><nlarge>0</nlarge><size>1360</size></pool>
<pool><nlarge>0</nlarge><size>1360</size></pool>
<pool><nlarge>0</nlarge><size>1360</size></pool>
尽管有3个large，再加上其他的小size，也都不够1g，断掉client之后，只有cscf->conf的统计了，58个large和9265个小size，没搞明白，nginx的内存缓存到什么地方了，很奇怪，也有可能我查问题的方向不对，问题是用咱们的module长时间的跑之后发现的内存泄漏，真心感谢您的及时反馈，如果方便的话，可以加您的微信 我的微信号是 longxx007 
sorry, I don't know whether you speak chinese. if NOT, I will try to describe this in English，looking forward to your reply. Thank you

**Comment by winshining** [comment]
cscf->pool不会被销毁，因为分配出来的内存使用后都被链接到内存链表了，以便循环使用。
你可以使用内存检测软件来检测内存泄露等问题。

**Comment by winshining** [comment]
经过微信沟通，请确保你自己添加的代码有无引入内存泄露。
从8月份起，每次代码修改都通过GCC自带的内存检测选项测试，没有报告内存泄露，double free等内存错误。商用的厂商也没有反馈内存泄露的问题。
请测试原生的nginx-http-flv-module，现在关闭这个issue，如果确实发现nginx-http-flv-module有内存泄露等问题，请告诉我，我再开启这个issue，谢谢！
