### ISSUE TITLE
flv.js无法播放

### ISSUE THREAD

**Issue by fire8862005** [winshining/nginx-http-flv-module#142]
flv live: client timed out (110: Connection timed out), client: 192.168.31.1, server: 0.0.0.0:1935
http地址：http://boccaccio.3322.org:12980/live?app=myapp&stream=ipc
现象：.在VLC播放器上可以正常播放，但是在flv.js上面打不开，想请教下这个是啥原因呢

**Comment by winshining** [comment]
日志已经写明原因了

**Comment by fire8862005** [comment]
回复这么快。。。感谢。如果我要解决这个是要从FFmpeg参数调整方面入手吗

**Comment by winshining** [comment]
出现这个问题，有如下原因：
1.服务器和客服端之间的网络不好，服务器在一定时间后无法感知客户端是否还active，超时关闭连接。
2.客户端的缓冲区满了，不接受新的数据，服务器在socket上一直不可写，一定时间后超时关闭连接。
3.请确保你的视频编码能被flv.js识别（其实是浏览器是否支持），但是这个可能性几乎不可能，因为如果flv.js不识别视频编码，最开始就会停止播放，断开连接，不会出现超时的问题。
