### ISSUE TITLE
HLS cleanup 不工作

### ISSUE THREAD

**Issue by xiangshengjye** [winshining/nginx-http-flv-module#143]
master_process off;
开启此配置之后, HLS cleanup 不工作, 不会清理失效的ts文件

**Comment by winshining** [comment]
清理工作是由cache manager process完成的，而cache manager process是master process fork而来，你配置了
    master_process off;
不会生成cache manager process，所以不会清理。

**Comment by gougehenhao** [comment]
生产出来的ts片，如何设置为不清理

**Comment by winshining** [comment]
@gougehenhao 
https://github.com/arut/nginx-rtmp-module/wiki/Directives#hls
