### ISSUE TITLE
如何以flv流格式的方式抓取nginx服务器上的某个MP4文件

### ISSUE THREAD

**Issue by web-pencil** [winshining/nginx-http-flv-module#146]
现在nginx服务器上有一个MP4文件，网页播放器使用flv.js框架。
当网页端请求nginx服务器的MP4文件时，希望nginx对MP4文件进行处理封装成FLV流格式进行数据传输，而不是mp4文件直接传输。
nginx-rtmp-module模块在rtmp配置中加个location，给它配个play地址就可以正常播放。
nginx-http-flv-module如何配置呢？
感谢！

**Comment by winshining** [comment]
rtmp配置块里没有location，笔误吧？应该是application，play播放用的是rtmp协议。
我不是很明白你为什么要把mp4转化成flv流？flv.js的工作就是把flv流转化为fmp4片段后再喂给video标签。Nginx有自带的模块原生支持点播mp4文件，且现在主流的浏览器已经原生支持播放mp4/fmp4文件了（大多数不支持H.265编码的视频），直接用浏览器通过http协议请求mp4然后播放不更好？你要说flv.js支持seek，pause等操作，浏览器也直接支持mp4的这些操作啊。
但是你确实要这么干，那可以查看nginx-rtmp-module的wiki，找到exec的说明，调用第三方软件将mp4文件转换为rtmp流，推给nginx-http-flv-module，再通过http-flv播放即可，这个圈子就绕大了。
直接的方法：mp4--(sendfile)-->Nginx--HTTP-->Browser
你想要的方法：mp4--(RTMP)-->Nginx(nginx-http-flv-module)--HTTP-FLV->flv.js--(fMP4)-->Browser

**Comment by web-pencil** [comment]
谢谢回复
的确是笔误
这个案例是为了方便测试，因为是要用flv.js播放摄像头传过来的数据，为了简化测试，想直接弄个自己摄像头拍摄的MP4文件作为数据源，进行兼容性测试
