### ISSUE TITLE
播放FLV时直接拉取FLV流，这样实现是否有可行性呢

### ISSUE THREAD

**Issue by spacewander** [winshining/nginx-http-flv-module#149]
目前 nginx-http-flv-module 似乎只支持在播放FLV时转换RTMP成FLV流。比如像这样的配置：
```nginx
        location /live {
            flv_live on; #open flv live streaming (subscribe)
        }
```
会去 1935 端口拉对应的 RTMP 流。
有没有可能实现直接拉 FLV 流的功能呢？（类似于 pull rtmp:// 那样的，多个客户端播放的时候，只用一个流来拉取）

**Comment by winshining** [comment]
没太懂你的意思，是以HTTP-FLV方式推流，HTTP-FLV方式播放吗？如果是这样，可以自行实现：

    ngx_int_t ngx_http_read_client_request_body(ngx_http_request_t *r, ngx_http_client_body_handler_pt post_handler);

中的post_handler回调函数，其他的功能可以参考RTMP框架的实现。

**Comment by spacewander** [comment]
多谢指点，我先自己实现一下试试看。
