### ISSUE TITLE
使用On_Play添加时间戳签名的问题

### ISSUE THREAD

**Issue by gesong2017** [winshining/nginx-http-flv-module#153]
nginx.conf参考了这个链接：
http://nginx-rtmp.blogspot.com/2013/06/secure-links-in-nginx-rtmp.html

使用VLC播放带签名的RTMP流正常工作，在flv.js上尝试给http-flv的播放地址后面添加签名，列如：http://192.168.0.1/live?port=1935&app=live&stream=camera?sign=xxxxxxxxxx&time=1585730400
结果flv.js页面上的日志显示
[MSEController] > MediaSource onSourceOpen
[IOController] > Loader error, code = -1, msg = Failed to fetch
[TransmuxingController] > IOException: type = Exception, code = -1, msg = Failed to fetch

查看nginx服务器访问日志，发现返回了501，也就是验证失败。想问下需要设置别的东西么？还是我的地址的格式写的不对？

**Comment by winshining** [comment]
URL格式错误
