### ISSUE TITLE
大佬，啥时候支持websocket

### ISSUE THREAD

**Issue by Lakeassal** [winshining/nginx-http-flv-module#154]
When you meet a bug, please open the issue including a title prefixed by '[bug]' and describe it as follows:

**Comment by winshining** [comment]
不会在开源版本中支持WebSocket。
这个项目开源近3年来，主要是我一个人维护，遇到了与很多其他个人开源项目类似的问题：社区参与度太低；另外，集成本模块的公司，包括HUAWEI，ZTE（信息来自网友，未确认），EasyNVR等从来没有资助或者回馈过代码。
我的精力和时间有限，不过欢迎PR，我乐意review代码和测试功能 :)
