### ISSUE TITLE
How to get HLS stats?

### ISSUE THREAD

**Issue by TheRealMattLear** [winshining/nginx-http-flv-module#155]
Hi,

The JSON /stat only provides information on RTMP connections but not HLS connections.

How could we see HLS connections?

**Comment by winshining** [comment]
Hi, HLS is not a stream based protocol and HLS specification has never defined some "commands" such as `play`, `stop`, `pause`, so it's difficult for server to identify whether an HLS request (actually a not long time HTTP request) is alive or not.
