### ISSUE TITLE
flv live: client timed out异常

### ISSUE THREAD

**Issue by chenjinli** [winshining/nginx-http-flv-module#156]
2020/04/02 22:41:13 [error] 4340#0: *2084 flv live: client timed out (110: Connection timed out), client: 30.55.176.88, server: 0.0.0.0:1935
hi，我用B站开源的flvjs播放，每次打开链接的时候经常会出现超时异常，大概会是什么原因导致的？

**Comment by chenjinli** [comment]
从抓包看，TCP链接已经建成功了

**Comment by winshining** [comment]
连接上长时间没有数据传输或者客户端长时间不接收数据，服务器就超时关闭连接。
这是防止有不怀好意的人发起连接后不传输任何数据，占用服务器资源。

**Comment by chenjinli** [comment]
这个可以理解。比较疑惑的是，看上去是服务器没有给播放器返回数据。直播源流是一直在往ngix推送的。会不会是有些情况下rtmp没有返回数据？您有没有碰到过类似问题？

**Comment by ondev** [comment]
我也遇到这个问题，不知道如何解决。

**Comment by favouriter** [comment]
nginx降到1.23就好了，1.24以上第一路视频可以播放，第二路就失败了

**Comment by agustik** [comment]
Is this fixed?

I got the same issue on 1.2.11, (nginx 1.27*) the servers returns 200 and then I get a error on my RTMP streamer that the server disconnected.

Will test this again using nginx 1.23.4.

**Comment by agustik** [comment]
> Is this fixed?
> 
> I got the same issue on 1.2.11, (nginx 1.27*) the servers returns 200 and then I get a error on my RTMP streamer that the server disconnected.
> 
> Will test this again using nginx 1.23.4.

I'll leave this for someone in the future.

The issue was worker_processes must be ONE. It seams like the workers are unable to connect to the rtmp source for streaming..  Quite strange.
