### ISSUE TITLE
发现http-flv延迟比较小一般在2秒，dplayer只支持带后缀的播放格式

### ISSUE THREAD

**Issue by 24021438** [winshining/nginx-http-flv-module#157]
via HLS
http://example.com[:port]/dir/streamname.m3u8
hls有播放地址可是延迟太高了。
http flv的播放地址构成是什么？
比如我推流到rtmp://192.168.10.188:1935/live/12345那么基于带.flv的播放地址是什么？

像腾讯的是https://3954.liveplay.myqcloud.com/live/3954_526644026_4000.flv这种

**Comment by cntrump** [comment]
举例：
HLS：
```
https://localhost:8443/live/hello.m3u8
```
HTTP-FLV
```
https://localhost:8443/flive?app=stream&stream=hello
```

**Comment by 24021438** [comment]
https://localhost:8443/flive?app=stream&stream=hello   推流跟播放不在一个服务器，http-flv   没有带后缀的取流吗？   .flv

**Comment by 24021438** [comment]
https://3954.liveplay.myqcloud.com/live/3954_526644026_4000.flv  推到腾讯播放地址就是带后缀的   .flv

**Comment by winshining** [comment]
HLS不适合做直播，延迟太大是众所周知的，有问题请去找Apple, Inc.。
此模块不支持带`.flv`后缀的访问方式，解决方法有两种：
1.修改源代码。
2.用Nginx的`rewrite`将带`.flv`的url重写为此模块支持的url。
