### ISSUE TITLE
关于Nginx反向代理

### ISSUE THREAD

**Issue by uebian** [winshining/nginx-http-flv-module#158]
需求：通过另一个Nginx（没有安装nginx-http-flv-module）代理内网中的Nginx服务器（安装了nginx-http-flv-module）的HTTP_FLV直播流。
我的尝试：在外部的Nginx服务器上进行了如下配置
`
location /live{
                proxy_pass http://x.x.x.x:8080/live/;
        }
`
但是无法正常通过flv.js访问，浏览器报错：[TransmuxingController] > Non-FLV, Unsupported media type!但将ip改为内网地址就可以正常访问。
应该怎样才能实现上述功能

**Comment by winshining** [comment]
通过`proxy_pass`访问上游服务器已验证过没有问题。
请查看上游服务器的访问日志，一般都是proxy转换url有错误。

**Comment by uebian** [comment]
感谢，我已经找到问题了

**Comment by unclesky4** [comment]
> 
> 
> 感谢，我已经找到问题了

通过nginx代理遇到同样问题，请问如何解决的？
