### ISSUE TITLE
rtmp 节配置pull rtmp源无法播放

### ISSUE THREAD

**Issue by xeonye** [winshining/nginx-http-flv-module#16]
配置pull流，vlc无法播放

**Comment by winshining** [comment]
pull用的如果是rtmp://live.hkstv.hk.lxdns.com/live/hks，已经验证是有问题，nginx-http-flv-module没有处理onBWDone等指令的handler，后续会添加上

**Comment by winshining** [comment]
@xeonye 这个问题已经修复，造成不能播放的原因请查看引用。

**Comment by zero863** [comment]
@xeonye 您好，想请问您fork的项目https://github.com/xeonye/WebRTC-1.git是否调试通过了呢？如果通过了，能否给予一定指导，我在这遇到困难，node.js出错，不胜感激
