### ISSUE TITLE
ffmpeg长时间推流后延迟增长到30s左右，刷新浏览器恢复正常的原因？

### ISSUE THREAD

**Issue by Sammy-Lee-T** [winshining/nginx-http-flv-module#161]
配置文件用的是首页给的配置，几乎没做改动。
请教一下，为什么ffmpeg长时间推流后延迟增长到30s左右，刷新谷歌浏览器恢复正常，这可能是哪里的原因呢？

**Comment by winshining** [comment]
因为网络状况不会一直都很好。网络状况不好的时候，服务器会缓存数据，浏览器会等待，等到网络状况好的时候服务器会加快发送数据，但是浏览器不会自动加快播放速率，所以需要对浏览器播放插件(如[flv.js](https://github.com/bilibili/flv.js))添加追帧功能，详情请自行查询。

**Comment by Sammy-Lee-T** [comment]
感谢大佬回答，研究了一下，flv.js追帧功能可以有效解决延迟问题，当判断延迟超过一定时间，就重置下，此举顺便可以解决缓存问题。
但有一点需要指出，我们测试的是局域网，与网络状况不好应该关系不大。
再次感谢！

**Comment by winshining** [comment]
就算服务器和浏览器在localhost上都还可能出现丢包的情况，所以不要对局域网期望过高。TCP协议保证数据可靠送达，所以基于TCP协议的或多或少都会出现这个问题。
