### ISSUE TITLE
多用户录制同一个流的问题

### ISSUE THREAD

**Issue by gesong2017** [winshining/nginx-http-flv-module#162]
查看了下nginx-rtmp-module录制功能的配置，发现它的录制功能的设计是针对流的，因此当多个用户观看同一个视频流时，每个用户都想对这个流进行录制的话，只有第一个人发出的start请求是有效的。想问下有没有好办法让每个用户可以录制同一个流，并且每个用户可以自由控制录制的开始和停止，录制出来的文件也各不相同

**Comment by winshining** [comment]
录制相关的请求是用HTTP协议实现的，而HTTP协议是无状态的，nginx-http-flv-module无法区分哪个请求属于哪个用户，也无法知道某个请求之前干了些什么，之后要干什么。

**Comment by gesong2017** [comment]
> 录制相关的请求是用HTTP协议实现的，而HTTP协议是无状态的，nginx-http-flv-module无法区分哪个请求属于哪个用户，也无法知道某个请求之前干了些什么，之后要干什么。

感谢解答，既然确定了录制模块的局限性我打算把录制的请求发送给服务器上的一个程序调用ffmpeg去操作了
