### ISSUE TITLE
How to configure RTMP streaming function with nginx?

### ISSUE THREAD

**Issue by E3V3A** [winshining/nginx-http-flv-module#165]
Hi!

We are trying to implement your RTMP streaming functionality in [nginx 1.18.0](http://nginx.org/download/nginx-1.18.0.zip), which are showing that it's supposedly compiled with `--with-http_flv_module`. However, including the config from your [readme](https://github.com/winshining/nginx-http-flv-module) doesn't work. Saying that the rtmp directive etc, are not recognized.

```bash
nginx version: nginx/1.18.0
built by cl 16.00.40219.01 for 80x86
built with OpenSSL 1.1.1f  31 Mar 2020
TLS SNI support enabled

configure arguments:
 --with-cc=cl
 --builddir=objs.msvc8
 --with-debug
 --prefix=
 --conf-path=conf/nginx.conf
 --pid-path=logs/nginx.pid
 --http-log-path=logs/access.log
 --error-log-path=logs/error.log
 --sbin-path=nginx.exe
 --http-client-body-temp-path=temp/client_body_temp
 --http-proxy-temp-path=temp/proxy_temp
 --http-fastcgi-temp-path=temp/fastcgi_temp
 --http-scgi-temp-path=temp/scgi_temp
 --http-uwsgi-temp-path=temp/uwsgi_temp
 --with-cc-opt=-DFD_SETSIZE=1024
 --with-pcre=objs.msvc8/lib/pcre-8.44
 --with-zlib=objs.msvc8/lib/zlib-1.2.11
 --with-http_v2_module
 --with-http_realip_module
 --with-http_addition_module
 --with-http_sub_module
 --with-http_dav_module
 --with-http_stub_status_module
 --with-http_flv_module                  <----------- THIS !  ---------
 --with-http_mp4_module
 --with-http_gunzip_module
 --with-http_gzip_static_module
 --with-http_auth_request_module
 --with-http_random_index_module
 --with-http_secure_link_module
 --with-http_slice_module
 --with-mail
 --with-stream
 --with-openssl=objs.msvc8/lib/openssl-1.1.1f
 --with-openssl-opt='no-asm no-tests -D_WIN32_WINNT=0x0501'
 --with-http_ssl_module
 --with-mail_ssl_module
 --with-stream_ssl_module
```

Any idea how to implement and configure this?

### Expected behavior

Expect that the config file in your README, should work on nginx 1.18.0.

### Actual behavior

Say that config file is invalid or doesn't recognize the shown directives.
```
2020/05/02 05:04:54 [emerg] 14036#16000: unknown directive "flv_live" in D:\avatarify\nginx/conf/nginx.conf:40
2020/05/02 05:06:16 [emerg] 6068#10104: unknown directive "rtmp_stat" in D:\avatarify\nginx/conf/nginx.conf:65
```

### Steps to reproduce the behavior 

- Install nginx 1.18.0
- Copy nginx.conf from your README and replace in `./nginx/conf/nginx.conf`
- Run: `./nginx -t`

**Comment by winshining** [comment]
Well, the module ngx_http_flv_module is not nginx-http-flv-module.
The name of this module is ngx_http_flv_live_module.

**Comment by winshining** [comment]
You can compile the module with Nginx as `Build` writes in README.md.
