### ISSUE TITLE
能支持把url转为 http://xxx/[id] 形式吗？而不是 ?id=xxx

### ISSUE THREAD

**Issue by MaJiaXuan** [winshining/nginx-http-flv-module#168]
When you meet a bug, please open the issue including a title prefixed by '[bug]' and describe it as follows:
能支持把url转为 http://xxx/[id] 形式吗？而不是 ?id=xxx

**Comment by winshining** [comment]
1. 使用Nginx的[rewrite](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#rewrite)将URL重写为本模块支持的格式。
2. 修改源代码支持。
