### ISSUE TITLE
如何能够在http请求过来后将http参数动态填入到ffmpeg推流命令中

### ISSUE THREAD

**Issue by GPSGH** [winshining/nginx-http-flv-module#169]
描述: 按照现在的文档描述，在http请求发生前必须使用命令行进行ffmpeg推流，这样nginx才能识别。

但是如何能够控制web端传入参数时，自动使用ffmpeg推流，从而达到nginx实时查看效果呢？

**Comment by zhoujm00000** [comment]
exec_pull
