### ISSUE TITLE
RTMP身份认证

### ISSUE THREAD

**Issue by Creepercdn** [winshining/nginx-http-flv-module#173]
添加RTMP身份验证功能

**Comment by winshining** [comment]
请自行研究，on_xxx等http回调可以实现

**Comment by Creepercdn** [comment]
但是在on_publish中回调的信息中没有用户名以及密码（在OBS中已开启身份认证且已填写用户名和密码）
接收到的参数：```CombinedMultiDict([ImmutableMultiDict([]), ImmutableMultiDict([('app', 'myapp'), ('flashver', 'FMLE/3.0 (compatible; FMSc/1.0)'), ('swfurl', 'rtmp://127.0.0.1:1935/myapp'), ('tcurl', 'rtmp://127.0.0.1:1935/myapp'), ('pageurl', ''), ('addr', '127.0.0.1'), ('clientid', '321'), ('call', 'publish'), ('name', 'wow'), ('type', 'live')])])```
用FFMPEG：```ffmpeg -re -i wtf.mp4 -c copy -f flv rtmp://muffin:itsmuffintime@127.0.0.1/myapp/wow```
```CombinedMultiDict([ImmutableMultiDict([]), ImmutableMultiDict([('app', 'myapp'), ('flashver', 'FMLE/3.0 (compatible; Lavf58.29.100)'), ('swfurl', ''), ('tcurl', 'rtmp://127.0.0.1:1935/myapp'), ('pageurl', ''), ('addr', '127.0.0.1'), ('clientid', '327'), ('call', 'publish'), ('name', 'wow'), ('type', 'live')])])```
