### ISSUE TITLE
【windows】跪求一个已经完成编译的nginx文件

### ISSUE THREAD

**Issue by houxiyao** [winshining/nginx-http-flv-module#175]
【windows】有没有哪位大哥有编译好的nginx文件啊， 我这因为电脑原因折腾了很久，都编译不成功。现在比较着急用。。。不想再这上浪费时间了。

**Comment by houxiyao** [comment]
经过不懈努力终于完成了编译并已分享，有同样需求的朋友们可以去下载。
地址：https://download.csdn.net/download/weixin_39400186/12752019

**Comment by tomuGo** [comment]
> 经过不懈努力终于完成了编译并已分享，有同样需求的朋友们可以去下载。
> 地址：https://download.csdn.net/download/weixin_39400186/12752019

没了 兄弟
