### ISSUE TITLE
求助：播放端想获取当前播放点的timestamp应该怎么获取呢，就像rtmp一样，就是从直播开始到当前的时间

### ISSUE THREAD

**Issue by lxlnn** [winshining/nginx-http-flv-module#178]

**Comment by winshining** [comment]
nginx-http-flv-module 将每个播放的流的 timestamp 都调整为从0开始，所以不管 HTTP-FLV 流还是 RTMP 流，当前的 timestamp 就是从直播开始到当前的时间。
