### ISSUE TITLE
[bug] stat页面偶尔会出现已经销毁的live streams

### ISSUE THREAD

**Issue by craneding** [winshining/nginx-http-flv-module#181]
### 效果如下图：
![29BB8546-056F-4A0B-A710-10DA3513BAC5](https://user-images.githubusercontent.com/6929198/98654663-8ee02000-2379-11eb-8936-af44bc5c3446.png)
### 问题：
出现了clients是0的live streams，然后点击live streams的连接，一直无反应，刷新页面一直不会清除，nginx reload后就恢复了。该现象已经出现过多次。
### 相关版本
1. nginx 1.18.0
2. nginx-http-flv-module 1.2.8
3. gcc 4.4.7
### stat配置
```
  location /stat {
        rtmp_stat            all;
        allow                127.0.0.1;
        rtmp_stat_stylesheet stat.xsl;
        add_header           Access-Control-Allow-Origin *;
   }

   location /stat.xsl {
        root                 html;
   }
```

**Comment by Mactarvish** [comment]
我遇到了类似的问题，只要在nginx中配置了stat页面，uwsgi就无法正常返回页面中的元素，注释掉就正常了

**Comment by winshining** [comment]
Fixed, please try the latest commit.
