### ISSUE TITLE
nginx1.9.1 http-flv 1.2.7 HLS文件不自动删除

### ISSUE THREAD

**Issue by qythker** [winshining/nginx-http-flv-module#182]
是不是没配置对啊?
我关闭流后 在 stat页面流也不显示了
但是hls的文件夹却还存在.为什么会这样呢?

**Comment by qythker** [comment]
rtmp {
     server {

   out_queue           4096;
   out_cork            128;
   max_streams         32;
   #timeout             6s;
   #drop_idle_publisher 6s;
   #buflen 1000ms;
   #idle_streams off;
   chunk_size 8182;
   #ack_window 5000000;
   max_message 1M;
   publish_time_fix off;
        listen 1935;
        application streamweb {
                live on;
                #meta off;
              # gop_cache on;

        hls on;
        wait_key on;
        hls_fragment 3s;
        hls_playlist_length 9s;
        hls_continuous on;
        hls_fragment_naming system;
        hls_path /home/qiuyongtiana/StreamPush/StreamPush/webroot/hlsdata/;
        hls_cleanup on;
        hls_nested on;
                }
        }
}

**Comment by shibataJun** [comment]
文档不是有这个吗。   add_header 'Cache-Control' 'no-cache';
location /hls {
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }

            root /tmp;
            add_header 'Cache-Control' 'no-cache';
        }

**Comment by qythker** [comment]
哦,我改成FFMPEG了,
