### ISSUE TITLE
[bug] when installing, error: config was not found

### ISSUE THREAD

**Issue by terids** [winshining/nginx-http-flv-module#183]
I am trying to set this up for the first time. When trying to add the flv module (using the configure script) it complains that no config exists in the flv module folder, even though it does exist.

### Expected behavior / 期望行为
The configure script would execute without error.

### Actual behavior / 实际行为
I get the error as above.

### OS and Nginx version / 操作系统和Nginx版本号
Ubuntu 20.04.1 LTS
Nginx 1.18.0
http-flv-module 1.2.8

### Steps to reproduce the behavior / 复现问题步骤
Just followed the readme up to "./configure --add-module=/path/to/nginx-http-flv-module" this line.

**Comment by winshining** [comment]
Did you copy and paste `--add-module=/path/to/nginx-http-flv-module` without modification?
Please substitude your own directory for `/path/to`.
