### ISSUE TITLE
How do you playback streams across multiple domains.

### ISSUE THREAD

**Issue by TroyDota** [winshining/nginx-http-flv-module#188]
```
server {
    listen 1935;
    server_name domain1.com
    application live {
        live on;
        allow play 127.0.0.1;
        deny play all;
    }
}

server {
    listen 1935;
    server_name domain2.com

    application live {
        live on;
        allow play 127.0.0.1;
        deny play all;
    }
}
```

if i stream to the first domain and do
```ffprobe rtmp://127.0.0.1/live/xxx```
the stream exists and i get data.

This is not the same for if i were to stream to the second domain.

**Comment by winshining** [comment]
Well, the server cannot match the different `server` blocks according to IPs but domain names. 
If you want to stream to the second domain and play from it, please use domain name in url rather than IP:

    publish: ffmpeg -re -i media_file -c copy -f flv rtmp://domain2/live/xxx
    play: ffplay rtmp://domain2/live/xxx

**Comment by TroyDota** [comment]
I c thanks <2
