### ISSUE TITLE
obs无法推流

### ISSUE THREAD

**Issue by dreamfly32** [winshining/nginx-http-flv-module#189]
![image](https://user-images.githubusercontent.com/32086491/103343261-a2c91800-4ac6-11eb-9731-c50f2582e4dd.png)

折腾一天了，不知道问题出在哪。。。
换台机器还是一样。
nginx也换了，配置文件也是用的你的例子。（只是把1935的server_name注释掉了）

背景：
ubuntu18，nginx14，nginx16， nginx-http-flv-module最新，

nginx编译命令
./configure --prefix=/etc/nginx --add-module=/root/nginx-http-flv-module/ -pid-path=/run/nginx.pid
make && make install 

当推流格式为rtmp://192.168.0.87:1935/myapp 时，报上图错，且有nginx error日志
![image](https://user-images.githubusercontent.com/32086491/103343626-7b267f80-4ac7-11eb-8e3a-3fb3636d00a0.png)

当推流格式为rtmp://192.168.0.87:1935/myapp/test  时，报上图错，没有nginx error日志。

so，问题出在哪？

**Comment by winshining** [comment]
https://www.bilibili.com/video/BV1sJ411L7r8

**Comment by dreamfly32** [comment]
我的问题，obs没配置正确，啊啊啊啊啊啊啊啊
