### ISSUE TITLE
负载均衡怎么实现呢

### ISSUE THREAD

**Issue by xxoxx** [winshining/nginx-http-flv-module#190]
When you meet a bug, please open the issue including a title prefixed by '[bug]' and describe it as follows:
当你碰到一个bug，请在提出问题时以'[bug]'为前缀写明标题，并且像下面的内容一样描述它:

### Expected behavior / 期望行为
目前单台机器CPU有点高了。 想负载均衡怎么实现呢？网上搜索了一下没有发现有类似的解决办法。

**Comment by winshining** [comment]
[proxy_pass](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass)
[upstream](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#server)
