### ISSUE TITLE
Nginx core removed post_accept_timeout.

### ISSUE THREAD

**Issue by TzyHuan** [winshining/nginx-http-flv-module#191]
https://github.com/winshining/nginx-http-flv-module/blob/4b8f0085a4064ca32dbc0f8d1b86e73727741eb6/ngx_rtmp.c#L817

[Here](https://github.com/nginx/nginx/commit/2ec8fac2d6b8e5023c9894d10bc50d78e63f242c#diff-9450eecd83e011923d6b4cea72d7fc91b3bfaa924fb65e12de9d9d2511b202b6) is the commit of removing `post_accept_timeout` from Nginx source code.

I remove the line in `nginx-http-flv-module/ngx_rtmp.c` manually, or I can't build.

**Comment by winshining** [comment]
Fixed, thank you for posting the issue.
