### ISSUE TITLE
Hostname parser issue, confilict with docker-compose auto naming rules.

### ISSUE THREAD

**Issue by lclancey** [winshining/nginx-http-flv-module#192]
https://github.com/winshining/nginx-http-flv-module/blob/13be96d72d5163c4819830bfe925dc919364e41e/ngx_rtmp_parse.c#L123-L134

According to the codes above, RTMP server only accept a `request_line`'s hostname combined with  alphabet,number,dot(.) and  -.
  
In my case, I'm using docker-compose to create two dockers.
One, I call it HOST docker, is a nginx-http-flv-module docker, and docker-compose auto naming it something like `project_service_1` when deploy.
Then, while the other docker(ffmpeg docker, I call it CODEC docker) try to push stream using docker-to-docker-inside-bridge, its output_url would be  "rtmp://project_service_1:1935/myapp/mystream", which is not accept by the nginx-http-flv-module docker. 
My sollution is  adding a line `container_name: host` to the docker-compose.yaml, to force naming it.

My question is, will it has any bad consequence if simply replace
```
          if ((ch >= '0' && ch <= '9') || ch == '.' || ch == '-') {
```
with
```
          if ((ch >= '0' && ch <= '9') || ch == '.' || ch == '-' || ch == '_') {
```
?

**Comment by winshining** [comment]
It is historically assumed in RFC 952 that characters in a domain name should drawn from the alphabet (A-Z and a-z), digits (0-9), minus sign (-), and period (.).
Underscore (_) was not specially pointed out. No bad consequence has been posted yet until now. However, I advise you not to use an underscore in a domain name.
