### ISSUE TITLE
多页面访问flv.js+http-flv,第一个页面可以正常播放到结束，之后打开的页面会从头开始播放视频,1秒后卡住

### ISSUE THREAD

**Issue by gengquanying** [winshining/nginx-http-flv-module#199]
When you meet a bug, please open the issue including a title prefixed by '[bug]' and describe it as follows:
当你碰到一个 bug，请在提出问题时以 '[bug]' 为前缀写明标题，并且像下面的内容一样描述它:

### Expected behavior / 期望行为
多页面访问，各自能正常播放视频流

### Actual behavior / 实际行为
第一个用户能正常播放,之后打开的页面均卡在视频第一秒左右处

### Steps to reproduce the behavior / 复现问题步骤
后台通过ffmpeg推流, 命令为: 
ffmpeg -re -i /xxx/demo.wmv -c:v libx264 -preset:v ultrafast -f flv rtmp://127.0.0.1:1935/live/test

Nginx配置文件常规设置，参考过各种写法，特别是issues #116,需要的话我可以贴出来

前端通过flv.js拉流，第一个用户访问完全没有问题, 接下来如果有第二个用户和第一个用户差不多时间打开，那么也没问题，如果间隔一段时间比如5秒，那么第二个用户会看到视频最开头的一秒动画，然后就一直卡住

**Comment by winshining** [comment]
![1](https://user-images.githubusercontent.com/3250905/111342569-8b58fe80-86b5-11eb-9747-c9eb0d339f6b.png)
![2](https://user-images.githubusercontent.com/3250905/111345352-29e65f00-86b8-11eb-951d-aaf164551637.png)
![3](https://user-images.githubusercontent.com/3250905/111345388-31a60380-86b8-11eb-9dab-fac5445e8827.png)
注意这 3 个窗口与推流时间的对比，能得出第二个播放窗口大概是在第一个窗口打开后的 13s 以后打开的，第三个播放窗口大概是在第一个窗口打开后的 26s 以后打开的。另外，如果你用的是 Chrome 浏览器，它默认在播放有声音的视频时会强制挂起，禁止视频自动播放。

**Comment by 1121076248** [comment]
感谢，原来是谷歌的问题

**Comment by 1121076248** [comment]
![image](https://user-images.githubusercontent.com/19721126/111724004-618e0c00-885c-11eb-91d2-73fc3daff13d.png)
有3-4S的延迟，全电脑本机，可能是电脑配置不行
