### ISSUE TITLE
这个项目是不是用了BLSS的代码?

### ISSUE THREAD

**Issue by gnolizuh** [winshining/nginx-http-flv-module#2]

**Comment by winshining** [comment]
@gnolizuh gop_cache部分是用的BLSS的

**Comment by gnolizuh** [comment]
使用源码请阅读 https://github.com/gnolizuh/BLSS/blob/master/LICENSE

**Comment by winshining** [comment]
@gnolizuh LICENSE更新了，README.md也添加了链接，对应的文件也添加了Copyright信息

**Comment by gnolizuh** [comment]
谢谢合作
