### ISSUE TITLE
on_connect 事件响应出错

### ISSUE THREAD

**Issue by dft2000** [winshining/nginx-http-flv-module#20]
server 段出现写了
on_connect 事件之后，flv的播放出现，500内部错误
server段配置：
server {
                listen 1935;
                notify_method get;
                on_connect http://127.0.0.1/my_auth.php;
                ...
nginx日志：
"GET /flv?port=1935&app=live&stream=s1 HTTP/1.0" 500 193 "-" "NSPlayer/7.10.0.3059"
"GET /my_auth.php?app=live&flashver=flv_live%201.1&swfurl=&tcurl=http://*.*.*.*:80/live&pageurl=&addr=*.*.*.*&epoch=2385077356&call=connect&port=1935&app=live&stream=s1 HTTP/1.0" 200 0 "-" "-"
vlc错误日志：
access_mms error: error: HTTP/1.1 500 Internal Server Error
core error: open of `http://*.*.*.*/flv?port=1935&app=live&stream=s1' failed
版本：
nginx-rtmp-module 1.2.2, nginx 1.12.2

**Comment by winshining** [comment]
空了我看看这个问题

**Comment by winshining** [comment]
@dft2000 bug已修复，请用最新的代码测试，非常感谢提出这个问题

**Comment by dft2000** [comment]
测试🆗
