### ISSUE TITLE
nginx编译报错

### ISSUE THREAD

**Issue by 1121076248** [winshining/nginx-http-flv-module#200]
编译nginx-rtmp-model-1.2.1是成功的，并且也在网页上测试过rtmp的播放，用的obs推流，测试过正常，后面偶然看到了支持度更高的nginx-http-flv-model，就下载了最新版来，./configure是成功的，make失败了，不知道什么原因，版本在截图里面
![image](https://user-images.githubusercontent.com/19721126/111620780-1386f300-87df-11eb-85dd-32d625de327b.png)
![image](https://user-images.githubusercontent.com/19721126/111620655-eafef900-87de-11eb-8855-0f79edd9f474.png)

**Comment by winshining** [comment]
#191 & #194

**Comment by 1121076248** [comment]
感谢，issues默认是打开中的问题，所以我没有找到类似的方案，我也删除了这一行，就成功了。
