### ISSUE TITLE
【bug】  nginx-http-flv-module  Alpine 编译  has no member named 'post_accept_timeout'

### ISSUE THREAD

**Issue by livingkang** [winshining/nginx-http-flv-module#201]
When you meet a bug, please open the issue including a title prefixed by '[bug]' and describe it as follows:
当你碰到一个 bug，请在提出问题时以 '[bug]' 为前缀写明标题，并且像下面的内容一样描述它:

### Expected behavior / 期望行为
能够正确编译通过
https://github.com/alfg/docker-nginx-rtmp  能正确编译通过
里面的 nginx-rtmp-module  改成nginx-http-flv-module 模块的时候也能通过。

### Actual behavior / 实际行为
/tmp/nginx-http-flv-module-1.2.8/ngx_rtmp.c: In function 'ngx_rtmp_add_listening':
/tmp/nginx-http-flv-module-1.2.8/ngx_rtmp.c:817:7: error: 'ngx_listening_t' {aka 'struct ngx_listening_s'} has no member named 'post_accept_timeout'
ls->post_accept_timeout = 60000;
#13 85.29       |       ^~
#13 85.31 make[1]: *** [objs/Makefile:1358: objs/addon/nginx-http-flv-module-1.2.8/ngx_rtmp.o] Error 1
#13 85.31 make[1]: Leaving directory '/tmp/nginx-1.19.8'

### OS and Nginx version / 操作系统和 Nginx 版本号
nginx=1.19.8
ffmpeg=4.3.2
nginx-http-flv=1.2.8
### Configuration file / 配置文件
编译
 cd /tmp/nginx-${NGINX_VERSION} && \
  ./configure \
  --prefix=/usr/local/nginx \
  --add-module=/tmp/nginx-http-flv-module-${NGINX_HTTP_FLV_VERSION} \
  --conf-path=/etc/nginx/nginx.conf \
  --with-threads \
  --with-file-aio \
  --with-http_ssl_module \
  --with-debug \
  --with-cc-opt="-Wimplicit-fallthrough=0" && \
  cd /tmp/nginx-${NGINX_VERSION} && make && make install

### Steps to reproduce the behavior / 复现问题步骤
参考 https://github.com/alfg/docker-nginx-rtmp 

dockefile 
由之前的--add-module=/tmp/nginx-rtmp-module-${NGINX_RTMP_VERSION} 
改成
--add-module=/tmp/nginx-http-flv-module-${NGINX_HTTP_FLV_VERSION}

**Comment by winshining** [comment]
#191 #194 #200
都不在 issue 区找找就来提问吗？
