### ISSUE TITLE
rtmp拉流 後推流到指定rtmp 伺服器

### ISSUE THREAD

**Issue by djdjdjek** [winshining/nginx-http-flv-module#202]
各位好
我嘗試了些方式，但是我似乎無法在rtmp module 裡面 pull 一個rtmp 流publish 出去。
我設定過可以listen 1935 port 當被推流進來時publish 到多個下級server 是正常的

請問這是軟體限制嗎？

**Comment by winshining** [comment]
你好，软件没有限制。
你的问题描述不清楚，我只能猜测分为两种情况：

1. nginx-http-flv-module -- pull --> A -- publish --> B

![1m](https://user-images.githubusercontent.com/3250905/112502394-ff398c00-8dc4-11eb-90e0-ccf5f5b23841.png)

注意黄色方框里的 url，rtmp 和 http-flv 都没有问题。
红色方框里：ffmpeg -- publish (1935) --> nginx-http-flv-module -- pull (1935) --> ffmpeg -- publish (1995) --> nginx-http-flv-module -- publish (1995) --> ffplay

2. A -- pull -> nginx-http-flv-module -- publish --> B

![2m](https://user-images.githubusercontent.com/3250905/112503096-9d2d5680-8dc5-11eb-83e2-3d8062443240.png)

注意黄色方框里的 url，rtmp 和 http-flv 也都没有问题。
红色方框里：ffmpeg -- publish (1935) --> nginx-http-flv-module -- pull (1935) --> nginx-http-flv-module -- publish (1995) --> ffplay

配置如下：

```bash
    server {
        listen 1935;
        application myapp {
            live on;
        }
    }

    server {
        listen 1995;
        application myapp {
            pull rtmp://localhost/$app/$name;
            live on;
        }
    }
```

**Comment by djdjdjek** [comment]
你好
感謝作者迅速的回應

我想要的設定更類似您第二種情況，但是我有個rtmp 來源，並且不希望經由ffmpeg 轉發（根據我測試這至少會多3秒延遲）。
詳細配置如下

”rtmp source“   <=pull=  “第一台nginx-http-flv-module” =publish=> “第二台nginx-http-flv-module”


我無法設定出 “第一台nginx-http-flv-module”  所需要的配置，只要pull， 就無法publish，不知道有沒有別的方式達成這個功能

**Comment by djdjdjek** [comment]
類似這種配置，測試是無效的
        application live {
            live on;
            pull rtmp://source domain/live/720p;
            push rtmp://next layer nginx server domain:1935/live/;
        }

**Comment by winshining** [comment]
也没问题，见下面的截图，黄色方框里表示 rtmp 和 http-flv 都可以正常播放，红色方框里是配置(抹去了一部分 ip 地址)，白色方框里是 tcp 连接情况(也抹去了一部分 ip 地址)。
![1m](https://user-images.githubusercontent.com/3250905/112654395-4dfd2980-8e8a-11eb-9d1d-ef3a89b7cc2c.png)
