### ISSUE TITLE
[bug]  linux nginx compile nginx-http-flv-module

### ISSUE THREAD

**Issue by LW-Francis** [winshining/nginx-http-flv-module#203]
i want to compile nginx-http-flv-module to nginx,but always have error like this

`
make -f objs/Makefile install
make[1]: Entering directory '/home/liuwuchuhao/soft/nginx-1.19.6'
test -d '/home/liuwuchuhao/soft/nginx-1.19.6/' || mkdir -p '/home/liuwuchuhao/soft/nginx-1.19.6/'
test -d '/home/liuwuchuhao/soft/nginx-1.19.6//sbin' \
        || mkdir -p '/home/liuwuchuhao/soft/nginx-1.19.6//sbin'
test ! -f '/home/liuwuchuhao/soft/nginx-1.19.6//sbin/nginx' \
        || mv '/home/liuwuchuhao/soft/nginx-1.19.6//sbin/nginx' \
                '/home/liuwuchuhao/soft/nginx-1.19.6//sbin/nginx.old'
cp objs/nginx '/home/liuwuchuhao/soft/nginx-1.19.6//sbin/nginx'
test -d '/home/liuwuchuhao/soft/nginx-1.19.6//conf' \
        || mkdir -p '/home/liuwuchuhao/soft/nginx-1.19.6//conf'
cp conf/koi-win '/home/liuwuchuhao/soft/nginx-1.19.6//conf'
cp: 'conf/koi-win' and '/home/liuwuchuhao/soft/nginx-1.19.6//conf/koi-win' are the same file
objs/Makefile:1583: recipe for target 'install' failed
make[1]: *** [install] Error 1
make[1]: Leaving directory '/home/liuwuchuhao/soft/nginx-1.19.6'
Makefile:11: recipe for target 'install' failed
make: *** [install] Error 2
`

linux version:
Linux master 4.15.0-140-generic #144-Ubuntu SMP Fri Mar 19 14:12:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by winshining** [comment]
```bash
cp conf/koi-win '/home/liuwuchuhao/soft/nginx-1.19.6//conf'
cp: 'conf/koi-win' and '/home/liuwuchuhao/soft/nginx-1.19.6//conf/koi-win' are the same file
```

So, why are they the same file? You meant want to install Nginx in the source directory?
