### ISSUE TITLE
[bug]Ubuntu安装报错

### ISSUE THREAD

**Issue by hu1240050829** [winshining/nginx-http-flv-module#204]
When you meet a bug, please open the issue including a title prefixed by '[bug]' and describe it as follows:
当你碰到一个 bug，请在提出问题时以 '[bug]' 为前缀写明标题，并且像下面的内容一样描述它:

make时，单独安装nginx没有问题，但是--add-module=nginx-http-flv-module 之后，则出现

make: *** No rule to make target 'build', needed by 'default'.  Stop.

Ubuntu14 / Nginx1.19.10

**Comment by winshining** [comment]
![image](https://user-images.githubusercontent.com/3250905/115986343-51e3af00-a5e2-11eb-82a1-44cde6e79a67.png)
