### ISSUE TITLE
[bug]make报错

### ISSUE THREAD

**Issue by hu1240050829** [winshining/nginx-http-flv-module#205]
make时提示：
/usr/local/nginx-file/nginx-http-flv-module-1.2.8/ngx_rtmp.c:817:7: error: 'ngx_listening_t {aka struct ngx_listening_s}' has no member named 'post_accept_timeout'
     ls->post_accept_timeout = 60000;
objs/Makefile:1302: recipe for target 'objs/addon/nginx-http-flv-module-1.2.8/ngx_rtmp.o' failed

**Comment by winshining** [comment]
#191 #194 #200 #201
