### ISSUE TITLE
stat 中的In bits/s 的大小取决于什么，可以认为控制的吗。这个好像会影响到视频的播放

### ISSUE THREAD

**Issue by LW-Francis** [winshining/nginx-http-flv-module#206]
stat 中的In bits/s 的大小取决于什么，可以认为控制的吗。这个好像会影响到视频的播放

**Comment by winshining** [comment]
那个表示推流码率，跟服务器没关系，其他问题请查看 README 或者 nginx-rtmp-module 的 README 和 Wiki

**Comment by LW-Francis** [comment]
我现在是使用javacv从摄像头进行读取帧，然后对帧进行处理后再推到nginx-http-flv-module,In bits/s的值有时大有时小，我想了解的是，这个推流码率主要是跟什么因素有关系
