### ISSUE TITLE
ffmpeg推流到nginx，出现阻塞

### ISSUE THREAD

**Issue by relic5** [winshining/nginx-http-flv-module#210]
测试方式是通过vlc->ffmpeg->nginx
正常推送一段时间后，ffmpeg控制台显示阻塞，需要强制结束
![image](https://user-images.githubusercontent.com/8554218/128337500-b6d4e74a-38d3-4694-a4b3-83ff221442bb.png)

调大chunk_size的数值，可以拉长正常推送的时间，但是最终还是会阻塞
nginx的配置是这样的
![image](https://user-images.githubusercontent.com/8554218/128337935-0a54d008-e564-45ff-bed4-e396b0f01e0d.png)
请问下这是什么原因。

**Comment by relic5** [comment]
ffmpeg的命令是这样的
ffmpeg -i rtsp://127.0.0.1:18554/demo -vcodec copy -an -f flv -y rtmp://127.0.0.1:1985/app1/live1

**Comment by winshining** [comment]
下面是我自己测试的截图，测试推流时间都超过 1 小时后然后手动 Ctrl+C 退出的：
首先是 mp4->ffmpeg->nginx
![file](https://user-images.githubusercontent.com/3250905/129467825-ea068f08-3abd-4b18-ba0d-0f39f49dcd23.png)
然后是 stream->ffmpeg->nginx
![stream](https://user-images.githubusercontent.com/3250905/129467826-f857a83d-ed4a-4e5b-a376-497bae177b19.png)

**Comment by winshining** [comment]
上述的测试采用跟你一样的配置。
你说的“阻塞”的打印，实际上是时间戳非递增打印的警告信息，跟服务器没关系。
另外，测试的时候请把 error_log 的打印级别调整为：
```
error_log logs/error.log info;
```
或者
```
error_log logs/error.log error;
```
