### ISSUE TITLE
[bug]使用ffmpeg推流一个mp3文件到nginx-http-flv-module生成的ts文件带视频信息，导致iphone12下播放有问题

### ISSUE THREAD

**Issue by ljwps** [winshining/nginx-http-flv-module#217]
When you meet a bug, please open the issue including a title prefixed by '[bug]' and describe it as follows:
当你碰到一个 bug，请在提出问题时以 '[bug]' 为前缀写明标题，并且像下面的内容一样描述它:
[bug]使用ffmpeg推流一个mp3文件到nginx-http-flv-module生成的ts文件带视频信息（HLS模式），导致iphone12下播放有问题，虽然ts里面视频信息宽高都为0并且没有码率，但iphone12会当作视频一直等待加载，需要点击播放并且拉动滚动条才能播放。
再次使用ffmpeg将ts文件去掉视频信息后播放正常。
### Expected behavior / 期望行为
m3u8可以直接播放
### Actual behavior / 实际行为
m3u8不可以直接播放
### OS and Nginx version / 操作系统和 Nginx 版本号
Linux version 3.10.0-1127.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) )
nginx-http-flv-module 1.2.9, nginx 1.21.1
### Steps to reproduce the behavior / 复现问题步骤
1、启动nginx+nginx-http-flv-module
2、推流ffmpeg -re -stream_loop -1 -i i:/我的/Desktop/a.mp3 -acodec aac -f flv rtmp://192.168.5.141:9004/hls/123456
3、使用iphone12访问m3u8地址，即可复现
![image](https://user-images.githubusercontent.com/18318466/145017133-bf2de96a-d935-492f-9e28-5b3e7a65a119.png)
**上图为第二步，点了播放按钮并且拖动滚动条后，如下图**
![image](https://user-images.githubusercontent.com/18318466/145017168-68336577-c26d-49e1-9294-44ac29c457e5.png)
**虽然通过点击+拖动滚动条能播放了，但实际上iphone12还是当作一个视频在播放**

**Comment by chundonglinlin** [comment]
hls写ts片时头里patpmt是固定的ngx_rtmp_mpegts_header，如：
https://github.com/winshining/nginx-http-flv-module/blob/ddc0df9d96b4d7045782cf944e42dac585906b3c/hls/ngx_rtmp_mpegts.c#L48
你应该重新生成pmt部分的信息替换h264和aac

**Comment by ljwps** [comment]
> hls写ts片时头里patpmt是固定的ngx_rtmp_mpegts_header，如：
> 
> https://github.com/winshining/nginx-http-flv-module/blob/ddc0df9d96b4d7045782cf944e42dac585906b3c/hls/ngx_rtmp_mpegts.c#L48
> 
> 
> 你应该重新生成pmt部分的信息替换h264和aac

感谢回复！
我看到nginx-rtmp-module也被提了个这个问题

**Comment by winshining** [comment]
Fixed. Please fetch the latest code to test.
