### ISSUE TITLE
请问下关于Big-Endian的支持

### ISSUE THREAD

**Issue by reusu** [winshining/nginx-http-flv-module#221]
When you meet a bug, please open the issue including a title prefixed by '[bug]' and describe it as follows:
当你碰到一个 bug，请在提出问题时以 '[bug]' 为前缀写明标题，并且像下面的内容一样描述它:

手里有一个mips的设备，编译了模块并且成功启动NGINX之后，无法进行推流
DEBUG显示太大的数据包
2022/03/31 08:27:47 [info] 873#0: *3 client connected '172.20.21.100'
2022/03/31 08:27:47 [info] 873#0: *3 too big message: 67108864, 1048576, client: 172.20.21.100, server: 0.0.0.0:1935
2022/03/31 08:27:47 [info] 873#0: *3 disconnect, client: 172.20.21.100, server: 0.0.0.0:1935
2022/03/31 08:27:47 [info] 873#0: *3 deleteStream, client: 172.20.21.100, server: 0.0.0.0:1935

### Expected behavior / 期望行为
正常推流
### Actual behavior / 实际行为
无法推流
### OS and Nginx version / 操作系统和 Nginx 版本号
OpenWRT 22.02.1/Linux 5.4.154 - nginx version: nginx/1.19.6 (x86_64-pc-linux-gnu) 
### Configuration file / 配置文件
使用README给的配置文件测试
### Steps to reproduce the behavior / 复现问题步骤
就是怎么运行怎么不行

**Comment by winshining** [comment]
我手头没有大端模式的 CPU，所以暂时无法修改。

I have no big-endian mode CPU at hand, so it will not be fixed temporarily.

**Comment by reusu** [comment]
https://github.com/reusu/nginx-http-flv-module/commit/f8c8ecb2ad5c2badf8b4515d05ee520824a366f8
暂时能跑了 BE的设备不多就算了 自己改改用

**Comment by winshining** [comment]
你好，昨天我把代码改了一下，但是我手里没有大端模式的 CPU，无法验证，你能帮忙验证一下吗？谢谢！
代码分支：https://github.com/winshining/nginx-http-flv-module/tree/endian
