### ISSUE TITLE
[Question] Any existing issues with Disk I/O and this module?

### ISSUE THREAD

**Issue by jyelloz** [winshining/nginx-http-flv-module#232]
Hi, I am working on a project that relies on this module to accept input RTMP streams and forward them elsewhere on a local network.
Lately, a problem has been identified where occasionally some live streams perform poorly, specifically viewers will experience higher than normal lag and unstable framerates after the stream has been running for a few hours.
Observing the host, one can see increased disk I/O around the time when the performance degrades, though the system CPU or memory usage does not change significantly during this time. Nginx is the only significant process running on the host.
A few possibilities have been considered as the cause. First, the server is currently configured to write its access log to stdout. 
Second, the server is configured with HLS enabled which writes to the disk during streaming.
Aside from those two, which have been explicitly configured and can be easily changed, are there any other scenarios where this module will write to disk while relaying an RTMP stream?

Thanks.

**Comment by winshining** [comment]
Hello!
If `error_log` and `access_log` directives were set properly in the configuration file, writing to access.log and error.log would not be the bottleneck.
Receiving and relaying RTMP streams only affect CPU and memory but not disk I/O.
Maybe writing to/reading from `.ts` increased disk I/O.

More information is needed to find the reason.
