### ISSUE TITLE
[question] Address name in live statistics

### ISSUE THREAD

**Issue by moonlightes** [winshining/nginx-http-flv-module#233]
Is it possible to somehow change the name of the stream, in the statistics? Change the address field to text or somehow add text for differences.
![Снимок](https://user-images.githubusercontent.com/12709475/221332644-435244e3-64b5-4b50-8fed-fa778f34a095.PNG)

**Comment by winshining** [comment]
No. The field is **Address**, not the name of stream and it is on the upper left, which is `stream`.

**Comment by moonlightes** [comment]
In nginx rtmp, in the address field, the domain was written which was specified for the push directive, which made it clear where the problem occurs (for example, frame loss). By ip addresses it is difficult to distinguish rtmp services where restream is conducted. Isn't there some way to name the client?
