### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by han4235** [winshining/nginx-http-flv-module#24]
ngx_http_flv_live_module.c:653: error: ‘NGX_HTTP_SERVER_TOKENS_ON’ undeclared (first use in this function)
ngx_http_flv_live_module.c:656: error: ‘NGX_HTTP_SERVER_TOKENS_BUILD’ undeclared (first use in this function)

应该是nginx版本的适配问题， 1.11系列的版本 会出现类似的问题

**Comment by winshining** [comment]
已修复
