### ISSUE TITLE
[bug] with stat info with multi config files

### ISSUE THREAD

**Issue by masternet0** [winshining/nginx-http-flv-module#240]
Hello,
There a bug in stat json info not show all users info when use multi vhost files for rtmp, its just show one user data only is last one

For example:
if you have multi rtmp vhost files like
/etc/nginx/conf/user1.conf
/etc/nginx/conf/user2.conf
/etc/nginx/conf/user3.conf

The stat url show only the data for user3
Need fix this to show all data for all config files 

Thank you
Regards

**Comment by winshining** [comment]
My config files:

user1.conf:

    server {
        listen 1935;
        server_name localhost;

        application myapp {
            live on;
        }
    }

user2.conf:

    server {
        listen 1935;
        server_name localtest; # actually 127.0.0.1

        application myapp {
            live on;
        }
    }

nginx.conf:

rtmp {
    ...;

    include user1.conf;
    include user2.conf;
}

They have the same port (1935) but different server names (localhost & localtest).

publish:

    ffmpeg -re -i workspace/nginx/media/xxx.mp4 -c copy -f flv rtmp://localhost/myapp/mystream
    ffmpeg -re -i workspace/nginx/media/xxx.mp4 -c copy -f flv rtmp://localtest/myapp/mystream

play:

    ffplay rtmp://localhost/maypp/mystream
    ffplay rtmp://localtest/myapp/mystream

The following is screenshot:

![stat](https://github.com/winshining/nginx-http-flv-module/assets/3250905/b82788ab-78c9-4e50-881a-d2fb6edb1ae5)

It's OK.

Please make sure browser cache is cleared or provide more information.

**Comment by masternet0** [comment]
Thank you for your response 
may be because you used same port
my case each user use its own port

**Comment by winshining** [comment]
In fact, if different ports are configured, `server_name` are useless.
It's OK still:
![stat2](https://github.com/winshining/nginx-http-flv-module/assets/3250905/d3c0a275-11f3-422c-8fe4-0f8d196fd6bb)

**Comment by winshining** [comment]
If you reproduce the bug, please let me know, I will reopen this issue. Thanks in advance.
Note: vhost functions improperly in multi-processes mode.

**Comment by winshining** [comment]
@masternet0 Hello, you can see `bw_audio` and `bw_video` in the following screenshot:
![stat_json](https://github.com/winshining/nginx-http-flv-module/assets/3250905/ed48d949-7536-40af-94b1-626354ada616)
