### ISSUE TITLE
[question]  http://example.com[:port]/dir/streamname.m3u8 unable to play

### ISSUE THREAD

**Issue by ZJDATY** [winshining/nginx-http-flv-module#248]
When you meet a bug, please open the issue including a title prefixed by '[bug]' and describe it as follows:
(当你碰到一个 bug，请在提出问题时以 '[bug]' 为前缀写明标题，并且像下面的内容一样描述它):

### Expected behavior (期望行为)
`http://127.0.0.1:80/tmp/hls`
`http://127.0.0.1:80/tmp/hls/hls.m3u8`
`http://127.0.0.1:80/tmp/hls.m3u8`

I have tried these connections and none of them can play
### OS and Nginx version (操作系统和 Nginx 版本号)
win11
nginx 1.25.2
nginx-http-flv-module-1.2.11
openssl-3.2.0-alpha2
pcre2-10.42
zlib-1.3
### Configuration file (配置文件)
I made several changes to the sample program,

appname   myapp -> live

all path  /tmp -> tmp (Using/tmp will result in an error, but if I change it to tmp, there will be no error reported. At the same time, I also created tmp/hls and tmp/dash in the root directory of nginx.)

```
worker_processes  1; #should be 1 for Windows, for it doesn't support Unix domain socket
#worker_processes  auto; #from versions 1.3.8 and 1.2.5

#worker_cpu_affinity  0001 0010 0100 1000; #only available on FreeBSD and Linux
#worker_cpu_affinity  auto; #from version 1.9.10

error_log logs/error.log error;

#if the module is compiled as a dynamic module and features relevant
#to RTMP are needed, the command below MUST be specified and MUST be
#located before events directive, otherwise the module won't be loaded
#or will be loaded unsuccessfully when NGINX is started

#load_module modules/ngx_http_flv_live_module.so;

events {
    worker_connections  4096;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    keepalive_timeout  65;

    server {
        listen       80;

        location / {
            root   /var/www;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        location /live {
            flv_live on; #open flv live streaming (subscribe)
            chunked_transfer_encoding  on; #open 'Transfer-Encoding: chunked' response

            add_header 'Access-Control-Allow-Origin' '*'; #add additional HTTP header
            add_header 'Access-Control-Allow-Credentials' 'true'; #add additional HTTP header
        }

        location /hls {
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }

            root tmp;
            add_header 'Cache-Control' 'no-cache';
        }

        location /dash {
            root tmp;
            add_header 'Cache-Control' 'no-cache';
        }

        location /stat {
            #configuration of streaming & recording statistics

            rtmp_stat all;
            rtmp_stat_stylesheet stat.xsl;
        }

        location /stat.xsl {
            root /var/www/rtmp; #specify in where stat.xsl located
        }

        #if JSON style stat needed, no need to specify
        #stat.xsl but a new directive rtmp_stat_format

        #location /stat {
        #    rtmp_stat all;
        #    rtmp_stat_format json;
        #}

        location /control {
            rtmp_control all; #configuration of control module of rtmp
        }
    }
}

rtmp_auto_push on;
rtmp_auto_push_reconnect 1s;
rtmp_socket_dir tmp;

rtmp {
    out_queue           4096;
    out_cork            8;
    max_streams         128;
    timeout             15s;
    drop_idle_publisher 15s;

    log_interval 5s; #interval used by log module to log in access.log, it is very useful for debug
    log_size     1m; #buffer size used by log module to log in access.log

    server {
        listen 1935;
        server_name www.test.*; #for suffix wildcard matching of virtual host name

        application live {
            live on;
            gop_cache on; #open GOP cache for reducing the wating time for the first picture of video
        }

        application hls {
            live on;
            hls on;
            hls_path tmp/hls;
        }

        application dash {
            live on;
            dash on;
            dash_path tmp/dash;
        }
    }

    server {
        listen 1935;
        server_name *.test.com; #for prefix wildcard matching of virtual host name

        application live {
            live on;
            gop_cache on; #open GOP cache for reducing the wating time for the first picture of video
        }
    }

    server {
        listen 1935;
        server_name www.test.com; #for completely matching of virtual host name

        application live {
            live on;
            gop_cache on; #open GOP cache for reducing the wating time for the first picture of video
        }
    }
}
```

### Steps to reproduce the behavior (复现问题步骤)
Use ffmpeg streaming.
`ffmpeg -re -i .\test.mp4 -c copy -f flv rtmp://127.0.0.1:1935/live/hls`

`rtmp://127.0.0.1:1935/live/hls`
and
`http://127.0.0.1:80/live?port=1935&app=live&stream=hls`
It can play normally.
But it cannot be played using the following one.
`http://example.com[:port]/dir/streamname.m3u8`

At the same time, the tmp/hls and tmp/dash in the root directory of nginx are both empty.

**Comment by winshining** [comment]
Make sure nginx has permission to access directotires you've configured.

**Comment by ZJDATY** [comment]
> Make sure nginx has permission to access directories you've configured.
还是用母语交流吧，外语容易词不达意，我用的是win11，我已经仔细检查，文件夹的权限都没有问题，我手动创建了tmp，运行程序它自动生成了hls和dash目录，说明不是文件夹权限问题。
我想请教一下 按照默认的conf配置，它是否会在hls下生成视频片段文件？
` http://example.com[:port]/dir/streamname.m3u8 `
还有一点，这里的dir ，是填 tmp 还是 tmp/hls 呢？
我还该怎么去排查问题呢？

**Comment by winshining** [comment]
![snapshot](https://github.com/winshining/nginx-http-flv-module/assets/3250905/117a153e-4cf5-4f29-85c4-d275d9d5acf6)

OS: Windows 11
Compiler: Visual Studio 2022
Media URL: http://localhost/hls/mystream.m3u8
Nginx version: 1.23.1
nginx-http-flv-module version: 1.2.11
Nginx config:

    http {
        # ...
        server {
            # ...
            location /hls {
                types {
                    application/vnd.apple.mpegurl m3u8;
                    video/mp2t ts;
                }

                root ./;

                add_header 'Cache-Control' 'no-cache';
            }
        }
    }
    
    rtmp {
        # ...
        server {
            # ...
            application hls {
                live on;
                hls on;
                hls_path ./hls;
            }
        }
    }

**Comment by ZJDATY** [comment]
> ![snapshot](https://user-images.githubusercontent.com/3250905/271788963-117a153e-4cf5-4f29-85c4-d275d9d5acf6.png)
> 
> OS: Windows 11 Compiler: Visual Studio 2022 Media URL: http://localhost/hls/mystream.m3u8 Nginx version: 1.23.1 nginx-http-flv-module version: 1.2.11 Nginx config:
> 
> ```
> http {
>     # ...
>     server {
>         # ...
>         location /hls {
>             types {
>                 application/vnd.apple.mpegurl m3u8;
>                 video/mp2t ts;
>             }
> 
>             root ./;
> 
>             add_header 'Cache-Control' 'no-cache';
>         }
>     }
> }
> 
> rtmp {
>     # ...
>     server {
>         # ...
>         application hls {
>             live on;
>             hls on;
>             hls_path ./hls;
>         }
>     }
> }
> ```

可以了，我之前用的是 

`ffmpeg -re -i .\test.mp4 -c copy -f flv rtmp://127.0.0.1:1935/live/hls`

以为它一条指令就可以产生所有的播放连接 。
现在看了大佬给的链接和配置文件，才明白，hls 和http-flv ，是在两个application  。必须把指令改成

`ffmpeg -re -i .\test.mp4 -c copy -f flv rtmp://127.0.0.1:1935/hls/hls` 

那我好奇 ，如果把 
        ```
 application hls {
            live on;
            hls on;
            hls_path ./hls;
        }
```
也放到 
         ```
application live {
          # . . . 
         }
```
是不是 只要
`ffmpeg -re -i .\test.mp4 -c copy -f flv rtmp://127.0.0.1:1935/live/hls`

就可以既有 **rtsp**  rtmp://127.0.0.1:1935/live/hls     
        又有   **http-flv**
       又有    **hls**   http: . .  .m3u8
