### ISSUE TITLE
ffmpeg [rtmp]: No default whitelist set

### ISSUE THREAD

**Issue by veasion** [winshining/nginx-http-flv-module#250]
通过 ffmpeg 往 nginx rtmp 模块推流时发现连接不上服务器（同样的代码在 windows 系统可以，linux 系统不行）。

### OS and Nginx version
centos 7,  nginx-1.21.1,  ffmpeg 6.0

nginx 配置
```
worker_processes 2;

events {
  worker_connections 1024;
}

rtmp {
  server {
    listen 1935;
    chunk_size 4096;
    allow play all;
    allow publish all;

    application live {
      live on;
      hls off;
      record off;
    }

  }
}
```

```python
command = ['ffmpeg',
		 '-y',
		 '-re',
		 '-an',
		 '-f', 'rawvideo',
		 '-vcodec', 'rawvideo',
		 '-s', '720x1280',
		 '-pix_fmt', 'bgr24',
		 '-r', '25',
		 '-i', '-',
		 '-c:v', 'h264',
		 '-b:v', '600k',
		 '-pix_fmt', 'yuv420p',
		 '-f', 'flv',
		 'rtmp://127.0.0.1/live/test'
		]
pipe = subprocess.Popen(command, stdin=subprocess.PIPE, shell=False)

pipe.stdin.write(frame_bytes)
```

ffmpeg debug 信息：
Opening an output file: rtmp://127.0.0.1/live/test.
[rtmp @ 0x15e3400] No default whitelist set
[tcp @ 0x15e3b00] No default whitelist set
[tcp @ 0x15e3b00] Original list of addresses:
[tcp @ 0x15e3b00] Address 127.0.0.1 port 1935
[tcp @ 0x15e3b00] Interleaved list of addresses:
[tcp @ 0x15e3b00] Address 127.0.0.1 port 1935
[tcp @ 0x15e3b00] Starting connection attempt to 127.0.0.1 port 1935
[rtmp @ 0x15e3400] Cannot open connection tcp://127.0.0.1:1935?tcp_nodelay=0
rtmp://127.0.0.1/live/test: Immediate exit requested

**Comment by FeiUmbrella** [comment]
请问您是什么原因导致推流时无法连接1935端口？
