### ISSUE TITLE
如何实现以http://[domain]/[app]/[streamname].flv这种格式播放flv流？配置文件该怎么配置

### ISSUE THREAD

**Issue by gougehenhao** [winshining/nginx-http-flv-module#26]
如何实现以http://[domain]/[app]/[streamname].flv这种格式播放flv流？配置文件该怎么配置

**Comment by winshining** [comment]
不支持这种格式，这是RTMP协议的格式，HTTP协议没有这种限制，要是设置成这样，很不灵活

**Comment by han4235** [comment]
http阶段的时候， 使用lua脚本， 将URL进行rewrite
