### ISSUE TITLE
two questions for me about control record

### ISSUE THREAD

**Issue by BinaryRyan** [winshining/nginx-http-flv-module#265]
1:calling control  record api and no content response
like this ` curl 'http://127.0.0.1:1056/control/record/start?app=live&name=4c9ce73065a644fb87867bcede069219&rec=rec'`
2:how to enable log for `NGX_LOG_DEBUG_RTMP`,I configure log with this directive `error_log logs/rtmp_control.log debug;`but I cannot get any useful message from this log file,and I have checked some source code in the function`ngx_rtmp_record_make_path`:
```
......
ngx_log_debug2(NGX_LOG_DEBUG_RTMP, s->connection->log, 0,
                   "record: %V path: '%V'", &rracf->id, path);
```
where's logs?
### Expected behavior (期望行为)
return the record path that in the server
### Actual behavior (实际行为)
no content 
### OS and Nginx version (操作系统和 Nginx 版本号)
Linux Centos8 nginx 1.22
### Configuration file (配置文件)
```conf
        listen       1056; 
        server_name  localhost;
        lua_need_request_body on; 
        gzip  on; 
        gzip_min_length  1k; 
        gzip_types  text/plain;
        gzip_comp_level  5;  
        add_header  Access-Control-Allow-Origin *;
        add_header  Access-Control-Allow-Credentials true;
        add_header  Access-Control-Allow-Headers *;
        add_header  Access-Control-Allow-Methods PUT,POST,GET,DELETE,OPTIONS;
        if ($request_method = OPTIONS) {
               return 204;
        }   
        location /stat {  
            rtmp_stat all;
        }   

        location /control { 
            rtmp_control all;
        }   
        location / { 
            root   html;
            index  index.html index.htm;
        }   

        location /video {
            root /data;
        }
```

**Comment by winshining** [comment]
1. DEBUG level log is eliminated by default, adding `--with-debug` option in `configure` step will make sense.
2. if you run nginx in multi-processes mode, record will not function when control requests arrive at a process which is not the publisher.

**Comment by BinaryRyan** [comment]
> 1. DEBUG level log is eliminated by default, adding `--with-debug` option in `configure` step will make sense.
> 2. if you run nginx in multi-processes mode, record will not function when control requests arrive at a process which is not the publisher.

user  root;
worker_processes  1;  
error_log  logs/error.log  debug;
this is my conf
nginx is not in multi-processes but one work process

calling start-rec-api when av_open successfuly

<img width="1383" alt="image" src="https://github.com/winshining/nginx-http-flv-module/assets/153162956/e5b18053-54a7-4179-be38-ee1b0420e7a2">
