### ISSUE TITLE
redirect with domain name? 

### ISSUE THREAD

**Issue by ingageco** [winshining/nginx-http-flv-module#266]
Hello! In the old module, on_publish required an IP address if you were returning a redirect. Is that still the case, or has this updated module changed it to allow domain names? 

Thank you!

**Comment by winshining** [comment]
Yes, domain names are supported. BUT normally, it is NOT recommended except you make sure that DNS servers can respond rapidly.
Refer to [notify_no_resolve](https://github.com/winshining/nginx-http-flv-module/wiki/Directives#notify_no_resolve) for details.
