### ISSUE TITLE
flv live: no on_play and no relay pulls, quit

### ISSUE THREAD

**Issue by jinlong0813** [winshining/nginx-http-flv-module#27]
您好，
我在linux下测试，昨天编译好的，RTMP和HTTP-FLV都可以正常播放。
今天只是重启了nginx进程，RTMP还可以播放，HTTP-FLV就报错flv live: no on_play and no relay pulls, quit。在Windows上测试也遇到了相同的问题。还请大神帮忙看下，万分感谢！
详细log如附件。
[error.log](https://github.com/winshining/nginx-http-flv-module/files/1927043/error.log)

**Comment by winshining** [comment]
配置能贴出来么？

**Comment by jinlong0813** [comment]
感谢您的回复，附件是最新的配置文件和对应的error.log
用OBS推的流rtmp://192.168.1.128:10935/myapp/test  RTMP可以播放， HTTP-FLV播的是http://192.168.1.128:10800/live?port=10935&app=myapp&name=test 但是没法播放。
[error.log](https://github.com/winshining/nginx-http-flv-module/files/1927317/error.log)

**Comment by jinlong0813** [comment]
配置文件好像发漏了
文件名末尾的格式.txt是我加的，不给传输.conf格式的。
[nginx.conf.txt](https://github.com/winshining/nginx-http-flv-module/files/1927321/nginx.conf.txt)

**Comment by winshining** [comment]
URL的参数写错了，是?port=10935&app=myapp&stream=test

**Comment by jinlong0813** [comment]
感谢感谢！没注意到，确实是这个问题~
