### ISSUE TITLE
怎么支持https

### ISSUE THREAD

**Issue by 0079123** [winshining/nginx-http-flv-module#32]
看了下实例只写了http播放的部分，请问下要怎么配置才能支持https？

**Comment by winshining** [comment]
nginx本身支持https，不过https方式我没有测试过，你可以试试，如果有问题可以反馈

**Comment by 0079123** [comment]
请问下 http的播放地址是怎么和rtmp的端口关联的？
我之前试过用srs拉flv nginx（https）反向代理srs的端口是可行的

**Comment by winshining** [comment]
从http请求的url中获取端口，然后在一个全局的结构体中查找rtmp对应的端口和使用的地址，以及rtmp使用的回调函数地址，它们相同就关联了，具体实现你可以看代码
