### ISSUE TITLE
关于https的支持

### ISSUE THREAD

**Issue by 0079123** [winshining/nginx-http-flv-module#33]
nginx部分配置了https

    server {
        listen       1443 ssl http2;
        server_name  localhost;

        ssl_certificate      server.crt;
        ssl_certificate_key  server.key;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        location / {
            root   html;
            index  index.html index.htm;
        }

        location /live {
            flv_live on; #打开HTTP播放FLV直播流功能
            chunked_transfer_encoding on; #支持'Transfer-Encoding: chunked'方式回复

            add_header 'Access-Control-Allow-Origin' '*'; #添加额外的HTTP头
            add_header 'Access-Control-Allow-Credentials' 'true'; #添加额外的HTTP头
        }
    }
用播放器直接播放没有问题，但是如果用flv.js会获取不到视频源，fetch 一直是0，请问能不能提供下解决思路

**Comment by winshining** [comment]
编辑了一下你的issue的格式。
你的意思是使用播放器可以以https方式可以播放http-flv直播对吧？如果是这样，要看flv.js是否支持HTTP 2.0

**Comment by 0079123** [comment]
对的，flv.js是支持的。之前测试过，用SRS3拉flv，再NGINX方向代理到SRS3的口就可以了（SRS有个自带的http服务），相当于SRS3和NGINX之间是http，出去之后是https。

**Comment by winshining** [comment]
后续我看看是什么问题

**Comment by winshining** [comment]
我试过了，nginx-http-flv-module支持vlc和flv.js以https方式访问http-flv直播流：
![20180520063211](https://user-images.githubusercontent.com/3250905/40273682-a7a47c40-5bf7-11e8-9760-d2bf1ec25457.png)
![20180520061616](https://user-images.githubusercontent.com/3250905/40273667-50ea02d0-5bf7-11e8-9b96-28f7155c1736.png)

**Comment by 0079123** [comment]
我觉得问题可能出在http2.0上，把h2配置去掉保留https 确实能播放
![123](https://user-images.githubusercontent.com/13670291/40286663-0b13219e-5cdb-11e8-9efb-18c546a47ef7.png)

**Comment by xiaooloong** [comment]
我也遇到了这个问题，确实是由于 http2 引起的。
环境：
* CentOS 7
* LibreSSL 2.7.4
* OpenResty 1.13.6.2
* nginx-http-flv-module 1.2.4
```
nginx version: openresty/1.13.6.2
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) 
built with LibreSSL 2.7.4
TLS SNI support enabled
configure arguments: --prefix=/opt/openresty/nginx --with-cc-opt='-O2 -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/opt/libressl/include' --add-module=../ngx_devel_kit-0.3.0 --add-module=../echo-nginx-module-0.61 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2rc3 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.13 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../ngx_stream_lua-0.0.5 --with-ld-opt='-Wl,-rpath,/opt/openresty/luajit/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/opt/libressl/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/opt/libressl/lib' --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-dtrace-probes --add-module=/root/openresty-1.13.6.2/nginx-http-flv-module-1.2.4 --with-stream --with-stream_ssl_module --with-http_ssl_module

```

**Comment by xiaooloong** [comment]
目前是在 https 的 server 下 proxy_pass 到 http 的 server 下的 `flv_live on;`

大概是这样：
```nginx
server {
    listen 127.0.0.1:8080 default;
    location ^~ /live {
        flv_live on;
    }
}
server {
    listen 443 ssl http2;
    location / {
        proxy_pass http://127.0.0.1:8080;
    }
}
```

**Comment by WayChan** [comment]
http2.0似乎真的支持有些许问题，删除http2字段，https可以拉取。加上之后，VLC跟chrome的flv.js都无法拉取。Chrome的调试日志会提示net::ERR_SPDY_PROTOCOL_ERROR

**Comment by q2758751404** [comment]
flv_live on;   这个开启之后 nginx就报405
![image](https://user-images.githubusercontent.com/49853938/87151095-d0868e80-c2e5-11ea-8fc9-2e0316da5f16.png)

**Comment by q2758751404** [comment]
我开启 https 之后  ,nginx就报405 请问知道怎么解决吗
![image](https://user-images.githubusercontent.com/49853938/87151293-2c511780-c2e6-11ea-85f2-ad0e6acdfe04.png)

**Comment by q2758751404** [comment]
我开启 https 之后  ,nginx就报405 请问知道怎么解决吗
![image](https://user-images.githubusercontent.com/49853938/87151293-2c511780-c2e6-11ea-85f2-ad0e6acdfe04.png)

**Comment by iScorpius** [comment]
> 目前是在 https 的 server 下 proxy_pass 到 http 的 server 下的 `flv_live on;`
> 
> 大概是这样：
> 
> ```nginx
> server {
>     listen 127.0.0.1:8080 default;
>     location ^~ /live {
>         flv_live on;
>     }
> }
> server {
>     listen 443 ssl http2;
>     location / {
>         proxy_pass http://127.0.0.1:8080;
>     }
> }
> ```

感谢提供思路！

**Comment by q2758751404** [comment]
感谢，虽然已经解决了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "George Hu"<notifications@github.com&gt;; 
发送时间: 2020年9月15日(星期二) 上午8:48
收件人: "winshining/nginx-http-flv-module"<nginx-http-flv-module@noreply.github.com&gt;; 
抄送: "斯丢的特"<2758751404@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [winshining/nginx-http-flv-module] 关于https的支持 (#33)





  
目前是在 https 的 server 下 proxy_pass 到 http 的 server 下的 flv_live on;
 
大概是这样：
 server {     listen 127.0.0.1:8080 default;     location ^~ /live {         flv_live on;     } } server {     listen 443 ssl http2;     location / {         proxy_pass http://127.0.0.1:8080;     } }
  
感谢提供思路！

**Comment by MyselfJar** [comment]
我也是啊  开启 http2.0，error 文件提示：  [error] 20808#13280: *79 flv live: HTTP version 0.9 or 2.0 not supported,
程序是不支持 http2.0 协议吧。
用 不开启http2.0 ，只用 https 是可以的。
或者用一个 http2.0 端口反代 flv 地址就行。。

**Comment by winshining** [comment]
此问题其实是 http/2.0 的问题，http/2.0 的实现要求强制加密。
鉴于社区参与度太低，"自主研发"的太多，不会支持了，原生支持的效果可以在 B站搜 nginx-http-live-module。

**Comment by HuYihe2008** [comment]
> 我开启 https 之后 ,nginx就报405 请问知道怎么解决吗 ![1594381777(1)](https://user-images.githubusercontent.com/49853938/87151513-91a50880-c2e6-11ea-9549-26be6be093cb.jpg)

我也是这样，有办法解决吗？
