### ISSUE TITLE
gop cache  播放假死

### ISSUE THREAD

**Issue by han4235** [winshining/nginx-http-flv-module#34]
hi， gopcache 貌似有点问题， 推流gop是2s的流的时候， 有很大的概率出现，多次打开的时候有部分链接瞬间卡死的情况， 流是正常的。

**Comment by winshining** [comment]
能贴一下配置文件么？

**Comment by han4235** [comment]
out_queue   4096;
out_cork    16;
sync 10ms;
idle_streams on;
chunk_size 65000;
drop_idle_publisher 100s;
max_message 512M;
max_streams 10000;
max_connections 10000;
publish_time_fix off;
publish_notify on;
push_reconnect 1s;
server {
    listen 1935;
    server_name www.laliu.com;
    access_log /usr/local/srs/log/access.log rtmp;
    application live {
        live on;
        interleave    on;
        wait_video   on;
        wait_key     on;
        allow play all;
        allow publish all;
        gop_cache on;
        pull xxxx tcUrl=rtmp://www.tuiliu.com/live;
    }
}

**Comment by han4235** [comment]
用的obs来推的流，obs可以设置gop。然后用http://www.cutv.com/demo/live_test.swf 拉流， 先开一个客户端， 然后用再开第二个客户端， 基本就能复现了

**Comment by winshining** [comment]
试过了，在obs中设置gop为2s，然后实时从摄像头（家）输入，再推流到服务器（公司），开两个vlc和两个flv.js，至少各个播放器各10次停止再播放，没有出现卡死的情况，flv.js每次刷新会暂停（这个不知道是什么原因），但是点击播放键后就都可以流畅播放，swf没测试。

**Comment by han4235** [comment]
恩， 我这边是很容易复现， 正在跟踪代码，给你发了邮件， 你看下。

**Comment by han4235** [comment]
已经解决，  interleave 参数打开的原因，关闭就可以了， 但是有个问题，  这个参数怎么会跟gop有关系呢？如果把gop关闭， 这个参数即使打开也没有问题。

**Comment by winshining** [comment]
刚才去看了下gop_cache的代码，确实找不出哪儿有问题，看有没有其他的网友能找出来，有时候钻进去了出不来（只缘身在此山中）

**Comment by winshining** [comment]
Solved.
