### ISSUE TITLE
relay 配置proxy_pass 的时候关闭chunked vlc 播放器仍然无法播放。可否把把flv视为一个4g 文件。去掉chunked

### ISSUE THREAD

**Issue by tail35** [winshining/nginx-http-flv-module#35]
When you meet a bug, please open the issue including a title prefixed by '[bug]' and describe it as follows:

**Comment by winshining** [comment]
proxy_pass和chunked已经废弃，要向上游服务器推流和拉流，请用push和pull，chunked已由标准的Nginx配置项chunked_transfer_encoding取代，不设置这个配置项也可以，只是HTTP应答方式不同而已。

**Comment by tail35** [comment]
感谢。
