### ISSUE TITLE
rtmp流无法播放，http可以

### ISSUE THREAD

**Issue by lystormenvoy** [winshining/nginx-http-flv-module#37]
流由另一个服务器的nginx使用push推送
配置文件：
    #user  nobody;
    worker_processes  1;

    #error_log  logs/error.log;
    #error_log  logs/error.log  notice;
    error_log  logs/error.log  info;

    #pid        logs/nginx.pid;
    worker_rlimit_nofile 40960;

    events {
        use epoll;
        worker_connections  10240;
    }

    rtmp {
        server {
                listen 9492;
                chunk_size 4096;
                application live {
                        live on;
                        max_connections 10240;
                }
                application hls {
                        live on;
                        gop_cache on;
                        hls on;
                        hls_path /usr/local/nginx/html/app;
                        hls_fragment 3s;
                        hls_playlist_length 30s;
                        hls_sync 100ms;
                        meta copy;
                        recorder chunked {
                                record all;
                                #record_max_size 6200K;
                                record_interval 10s;
                                record_suffix -%Y-%m-%d-%H_%M_%S.flv;
                                record_path /AVA/data/Upload/Rec/Chunked;
                        }
                        recorder all {
                                record all;
                                record_suffix -%Y-%m-%d-%H_%M_%S.flv;
                                record_max_size 6200000K;
                                record_path /AVA/data/Upload/Rec;
                        }
                }
                application Upload {
                        play /ava_app/school/src/tomcat/webapps/admin/upload;
                }
        }
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;
        sendfile        on;
        keepalive_timeout  65;

        server {
            listen       9491;
            server_name  localhost;

            location / {
                root   html;
                index  index.html index.htm;
            }

            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   html;
            }

            location /live {
                flv_live on;
                chunked_transfer_encoding off;
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Credentials' 'true';
            }

            location /hls {
                        types {
                                #application/vnd.apple.mpegurl m3u8;
                                application/x-mpegurl m3u8;
                                video/mp2t ts;
                        }
                        alias /usr/local/nginx/html/app;
                }
            location /stat {
                rtmp_stat all;
                rtmp_stat_stylesheet stat.xsl;
            }
            location /stat.xsl {
                root html;
            }
        }
    }

**Comment by lystormenvoy** [comment]
ffmpeg 提示
ffmpeg -loglevel debug -i rtmp://192.168.2.71:9492/hls/lvs
ffmpeg version 2.6.3 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.4.7 (GCC) 20120313 (Red Hat 4.4.7-17)
  configuration: --prefix=/usr/local/ --enable-gpl --enable-version3 --enable-nonfree --enable-shared --enable-zlib --enable-bzlib --enable-libfaac --enable-libmp3lame --enable-libtheora --enable-libvo-aacenc --enable-libvorbis --enable-libx264 --enable-libxvid --enable-pic --enable-pthreads --enable-libdc1394 --enable-libass --enable-pic --enable-openssl --enable-libtwolame --enable-libspeex --enable-libfreetype
  libavutil      54. 20.100 / 54. 20.100
  libavcodec     56. 26.100 / 56. 26.100
  libavformat    56. 25.101 / 56. 25.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 11.102 /  5. 11.102
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Splitting the commandline.
Reading option '-loglevel' ... matched as option 'loglevel' (set logging level) with argument 'debug'.
Reading option '-i' ... matched as input file with argument 'rtmp://192.168.2.71:9492/hls/lvs'.
Finished splitting the commandline.
Parsing a group of options: global .
Applying option loglevel (set logging level) with argument debug.
Successfully parsed a group of options.
Parsing a group of options: input file rtmp://192.168.2.71:9492/hls/lvs.
Successfully parsed a group of options.
Opening an input file: rtmp://192.168.2.71:9492/hls/lvs.
[rtmp @ 0x1a326e0] Handshaking...
[rtmp @ 0x1a326e0] Type answer 3
[rtmp @ 0x1a326e0] Server version 13.14.10.13
[rtmp @ 0x1a326e0] Proto = rtmp, path = /hls/lvs, app = hls, fname = lvs
[rtmp @ 0x1a326e0] Server bandwidth = 5000000
[rtmp @ 0x1a326e0] Client bandwidth = 5000000
[rtmp @ 0x1a326e0] New incoming chunk size = 4096
[rtmp @ 0x1a326e0] Creating stream...
[rtmp @ 0x1a326e0] Sending play command for 'lvs'
[rtmp @ 0x1a326e0] Deleting stream...
rtmp://192.168.2.71:9492/hls/lvs: Invalid data found when processing input

**Comment by winshining** [comment]
编译的时候加--with-debug，然后在conf文件里的error_log最后加debug，重启，然后看打印日志哪儿有问题

**Comment by lystormenvoy** [comment]
debug日志刷得飞快啊，只能截最后出现我客户端IP的那部分了
2018/06/01 16:09:08 [debug] 17636#0: epoll: fd:14 ev:2019 d:00007FA976F11498
2018/06/01 16:09:08 [debug] 17636#0: epoll_wait() error on fd:14 ev:2019
2018/06/01 16:09:08 [debug] 17636#0: *2 recv: eof:1, avail:1
2018/06/01 16:09:08 [debug] 17636#0: *2 recv: fd:14 -1 of 138
2018/06/01 16:09:08 [info] 17636#0: *2 recv() failed (104: Connection reset by peer), client: 192.168.2.39, server: 0.0.0.0:9492
2018/06/01 16:09:08 [debug] 17636#0: *2 finalize session
2018/06/01 16:09:08 [debug] 17636#0: *2 post event 0000000001310B38
2018/06/01 16:09:08 [debug] 17636#0: timer delta: 0
2018/06/01 16:09:08 [debug] 17636#0: posted event 0000000001310B38
2018/06/01 16:09:08 [debug] 17636#0: *2 delete posted event 0000000001310B38
2018/06/01 16:09:08 [debug] 17636#0: *2 close session
2018/06/01 16:09:08 [info] 17636#0: *2 disconnect, client: 192.168.2.39, server: 0.0.0.0:9492
2018/06/01 16:09:08 [info] 17636#0: *2 deleteStream, client: 192.168.2.39, server: 0.0.0.0:9492
2018/06/01 16:09:08 [debug] 17636#0: *2 live: leave 'lvs'
2018/06/01 16:09:08 [debug] 17636#0: *2 create: stream_end msid=1
2018/06/01 16:09:08 [debug] 17636#0: *2 RTMP prep user (4) fmt=0 csid=2 timestamp=0 mlen=6 msid=0 nbufs=1
2018/06/01 16:09:08 [debug] 17636#0: *2 live: set active=0
2018/06/01 16:09:08 [debug] 17636#0: *2 RTMP send nmsg=1, priority=0 #14
2018/06/01 16:09:08 [debug] 17636#0: *2 record: close_stream
2018/06/01 16:09:08 [debug] 17636#0: *2 malloc: 000000000139AD70:660
2018/06/01 16:09:08 [debug] 17636#0: shmtx lock
2018/06/01 16:09:08 [debug] 17636#0: shmtx unlock
2018/06/01 16:09:08 [debug] 17636#0: *2 limit: dec conection counter: 1
2018/06/01 16:09:08 [debug] 17636#0: *2 event timer del: 14: 161392497
2018/06/01 16:09:08 [debug] 17636#0: *2 free: 0000000001396BE0, unused: 3526
2018/06/01 16:09:08 [debug] 17636#0: *2 free: 0000000001395BD0, unused: 2736
2018/06/01 16:09:08 [debug] 17636#0: *2 free: 000000000138DBC0
2018/06/01 16:09:08 [debug] 17636#0: *2 free: 000000000130E470, unused: 4000
2018/06/01 16:09:08 [debug] 17636#0: *2 close connection
2018/06/01 16:09:08 [debug] 17636#0: *2 reusable connection: 0

**Comment by lystormenvoy** [comment]
配置文件就上面贴的那个

**Comment by winshining** [comment]
<img width="1094" alt="push" src="https://user-images.githubusercontent.com/3250905/40912626-b4578642-6824-11e8-8df3-a7b923d00ce3.png">
最上面的那个框表示本地服务器的配置，中间那个框表示往本地服务器推流，然后它再push到别的服务器，下面那个框表示从上面那个服务器请求RTMP流，没有问题
