### ISSUE TITLE
关于开启GOP缓存之后客户端无法播放或导致崩溃的问题

### ISSUE THREAD

**Issue by plainheart** [winshining/nginx-http-flv-module#40]
尝试了很多版本的Nginx去编译http-flv模块，但始终发现一旦开启 `gop_cache on`， 客户端将无法正常播放，严重时甚至导致推流暂时断开，好在推流端有断开重连机制，否则连推流端都断了。从错误日志也无法看出有什么问题，烦请作者将您测试时nginx版本及编译配置选项告诉下，我再重新编译试试有没有问题，谢谢！

**Comment by plainheart** [comment]
经过再三测试，发现使用现有Github上最新源码编译不能正常播放，而使用1.2.3发行版可以正常播放（开启gop_cache情况下），但偶现客户端播放http-flv仍导致推流崩溃的问题（猜测可能是播放器问题，这个我再多换一些播放器试试），再一个就是使用http-flv模块编译之后，rtmp播放延迟要比nginx-rtmp-module 延迟更多（相比http-flv还是慢了几秒）

**Comment by winshining** [comment]
1.对nginx的版本没限制，nginx-1.11.x和nginx-1.13.x我都试过，编译选项就是README文件里写的。
2.版本1.2.3有严重的bug，运行崩溃和内存泄露，CPU使用率100%等问题。当时我自己的测试有限，很多场景无法覆盖，网友反馈bug后我才修复了。RTMP播放已经有厂商商用了（开gop_cache），但是HTTP-FLV播放（不开gop_cache）有个厂商还没给我反馈，这也是我迟迟不发版本1.2.4的原因。

**Comment by plainheart** [comment]
多次编译发现终于可用了，虽然gop实现了秒开，但同时也增加了播放延时，看来两者不能兼得啊。谢谢作者！我会关闭这个issue
