### ISSUE TITLE
只用 hls 观看 pull 流时不拉流

### ISSUE THREAD

**Issue by aushy** [winshining/nginx-http-flv-module#41]
live on;
pull rtmp://live.hkstv.hk.lxdns.com/live/hks name=hks static; 
hls on;

只用 hls 观看时，它不拉流；有 http-flv 或 rtmp 观看时才会拉。

windows
nginx-1.14
nginx-http-flv-module
openssl-1.1.0h
pcre-8.42
zlib-1.2.11

**Comment by winshining** [comment]
hls不是流式的，无法支持。

**Comment by aushy** [comment]
虽然hls不是流式的，但是也是可以支持的嘛。

**Comment by winshining** [comment]
正因为hls不是流式的，请求一个分段的http请求可能是短连接，下载完一个分段或者几个分段连接就断开了，pull连接跟着就断开，再退一步说，就算用长连接，请求hls的请求触发pull，这需要时间，hls延迟本来就让人无法接受，还加个1~2秒的等待，更让人无法忍受！

**Comment by aushy** [comment]
短连接 hls 的请求触发 pull，pull 持续时间可以参考 hls_playlist_length；多人通过 hls 观看时，只有第一人出现触发延迟，后来者不会出现多余的时间等待。

**Comment by winshining** [comment]
按照你说的，pull持续时间hls_playlist_length，然后就断开了，这之后就不会生成hls分段了，hls请求完了已经生成的分段，需要再次触发pull，这中间有个间隔时间，造成媒体流不连续，怎么办？

**Comment by aushy** [comment]
pull 持续时间可以参考 hls_playlist_length，不必等同，比如可以是它的2倍；多次请求 hls，pull 断开的时间相应的延后，媒体流就延续了。
