### ISSUE TITLE
[bug] $connections_active huge number

### ISSUE THREAD

**Issue by invalidtask** [winshining/nginx-http-flv-module#42]
Returning $connections_active in http call returns huge number (int64/long) instead of active connections. When server first starts it appears number is correct. 

### Expected behavior
Correct example: 1500. 

### Actual behavior
But instead getting following result: 18446744073709550135

### Steps to reproduce the behavior 
Server with few thousand http requests/active connections

nginx 1.13.12

**Comment by winshining** [comment]
The bug is fixed. Please fetch the latest code to test it.
Thank you for posting the issue.

**Comment by invalidtask** [comment]
Thank you!
