### ISSUE TITLE
chunked_transfer_encoding  off; 不起作用，抓包还是发chunk

### ISSUE THREAD

**Issue by tail35** [winshining/nginx-http-flv-module#46]
When you meet a bug, please open the issue including a title prefixed by '[bug]' and describe it as follows:

**Comment by winshining** [comment]
关闭chunked_transfer_encoding选项测试截图如下：
![no_chunked](https://user-images.githubusercontent.com/3250905/41811539-12ed05be-7744-11e8-8f83-af21c44829d5.png)
开启chunked_transfer_encoding选项测试截图如下（对于HTTP 1.1默认是开启的）：
![chunked](https://user-images.githubusercontent.com/3250905/41811543-2f21deda-7744-11e8-99b7-3708b0bf58e7.png)
测试播放器是VLC和flv.js，请保证你的配置正确
