### ISSUE TITLE
微信小程序 rtmp推流ok，flv播放 3005 3003 读写失败，握手失败 

### ISSUE THREAD

**Issue by qzytcl** [winshining/nginx-http-flv-module#52]
When you meet a bug, please open the issue including a title prefixed by '[bug]' and describe it as follows:

### Expected behavior
正常播放 rtmp推流
### Actual behavior
播放失败：error code 3005 读写失败，3003 服务器握手失败

**Comment by winshining** [comment]
你自己写的解析HTTP-FLV的微信小程序？

**Comment by qzytcl** [comment]
使用问题，服务端配置没问题，微信小程序 video 配置问题，打扰了

**Comment by cleexiang** [comment]
@qzytcl 请问是什么配置导致不能播放呢，遇到同样的问题
