### ISSUE TITLE
在调用ngx_rtmp_finalize_session的情况下，没有释放gop缓存

### ISSUE THREAD

**Issue by 2017yihe** [winshining/nginx-http-flv-module#54]
When you meet a bug, please open the issue including a title prefixed by '[bug]' and describe it as follows:

### Steps to reproduce the behavior 
![image](https://user-images.githubusercontent.com/41164696/43193354-69dd3db0-9032-11e8-8075-d292a390e650.png)

**Comment by winshining** [comment]
你这用的不是最新的代码，这块代码为什么这么改，可以查看这个issue #29 ，因为之前不知道是不是GOP缓存导致很费内存，所以将GOP缓存使用的内存独立出来了，它的释放不在这儿。后来找到了很费内存的原因，所以这块代码已经恢复到之前的版本了。
