### ISSUE TITLE
1.2.3的release版本 内存泄漏将近4G

### ISSUE THREAD

**Issue by 2017yihe** [winshining/nginx-http-flv-module#56]
When you meet a bug, please open the issue including a title prefixed by '[bug]' and describe it as follows:

### Steps to reproduce the behavior 
![image](https://user-images.githubusercontent.com/41164696/43248749-685f85c4-90eb-11e8-8e68-9e5f5ec2c77d.png)

使用了1.2.3的release版本，压测一个小时，内存泄漏将近4G

**Comment by winshining** [comment]
1.2.3版本是pre-release版本

**Comment by 2017yihe** [comment]
哪个版本没有问题???????

**Comment by winshining** [comment]
1.2.4有问题？

**Comment by winshining** [comment]
我建议你用最新的代码压测，因为1.2.4后又做了不少改动，先别加你的代码，如果有问题，我再开这个issue

**Comment by 2017yihe** [comment]
有跑1.2.4的版本，有两个问题 1、播放老是会断 ，在先播放后推流的情况不会断 2、gop 模块的ctx的pool为空，造成core

**Comment by winshining** [comment]
1.2.4的问题是怎么复现的？
