### ISSUE TITLE
推流路数多时，内存占用太高，疑似内存泄漏

### ISSUE THREAD

**Issue by luckywur** [winshining/nginx-http-flv-module#57]
目前在线不到90路推流，中间有陆续的推流、停止推流、再推流。内存占用14G。版本为1.2.4

![image](https://user-images.githubusercontent.com/26076241/43497411-8ef43af8-9574-11e8-8760-58cddb925751.png)

[view-source_192.168.0.101_stat.txt](https://github.com/winshining/nginx-http-flv-module/files/2247761/view-source_192.168.0.101_stat.txt)

**Comment by winshining** [comment]
怎么复现的？
你这图哪儿显示了内存占用14G？

**Comment by luckywur** [comment]
![image](https://user-images.githubusercontent.com/26076241/43503999-2f9bc632-9594-11e8-9cc5-489380caa159.png)

就只是用srs-bench并发推送很多路流。

**Comment by luckywur** [comment]
只是推流
推流和nginx是分离的。

**Comment by winshining** [comment]
我按照你说的试了，暂时复现不出来，推100路流，内存一直稳定在224M左右
另外，你用的是release里1.2.4的包还是源代码编译的？

**Comment by luckywur** [comment]
用的是release里1.2.4包编译的。等一下我用最新代码编译试一下

**Comment by winshining** [comment]
@luckywur 最新代码测试有问题么？

**Comment by luckywur** [comment]
要好很多，但是内存还是占用很高
![image](https://user-images.githubusercontent.com/26076241/43571109-b47e6078-966e-11e8-9d3e-ed832e21f53b.png)

`#user  nobody;
worker_processes 1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
        location /live {
            flv_live on;
            chunked_transfer_encoding  on; #open 'Transfer-Encoding: chunked' response

            add_header 'Access-Control-Allow-Origin' '*'; #add additional HTTP header
            add_header 'Access-Control-Allow-Credentials' 'true'; #add additional HTTP header
        }

        location /stat {

            rtmp_stat all;
            rtmp_stat_stylesheet stat.xsl;
        }

        location /stat.xsl {
            root /var/www/rtmp; 
        }

        location /control {
            rtmp_control all;
        }
    }
}

rtmp_auto_push on;
rtmp_auto_push_reconnect 1s;
rtmp_socket_dir /tmp;

rtmp {
    out_queue   4096;
    out_cork    8;
    max_streams 400;

    server {
        listen 1935;

        application hls {
            live on;
            hls on;
            hls_path /tmp/hls;
            gop_cache on; #open GOP cache for reducing the wating time for the first picture of video
            on_publish        http://127.0.0.1:8080/nvrEvent/live/publish;
            on_publish_done   http://127.0.0.1:8080/nvrEvent/live/publishDone;
            on_play           http://127.0.0.1:8080/nvrEvent/live/play; 
            on_play_done      http://127.0.0.1:8080/nvrEvent/live/playDone;
        }
    }
} `

这个是我的配置。目前测试方法是在on_play中调用其他应用进行推流，然后在on_play_done判断是否有其他用户，没有则停止推流，所以在测试的时候不停的推流、断开、再推流。

**Comment by luckywur** [comment]
发现疑似和hls有关系，我将配置的hls设置为off，内存占用才400M

**Comment by winshining** [comment]
你用nginx-rtmp-module对比测试一下吧，hls部分的功能我没动过，如果有同样的问题，就不是nginx-http-flv-module的bug了

**Comment by luckywur** [comment]
发现在未开hls情况下，推流时间长了后，不停的停止推流再推流，内存会不断上涨。没有推流数据后内存仍然没有回收
![image](https://user-images.githubusercontent.com/26076241/43631458-d5a0f2da-9735-11e8-9117-de37cfd318a1.png)

**Comment by winshining** [comment]
方便提供on_publish，on_publish_done，on_play和on_play_done的url内容么？

**Comment by luckywur** [comment]
代码有点多，
主要实现是on_play会判断该路流是否已经推送，推送了就直接返回ok，未推送则调用推送流程，返回ok
on_play_done是判断是否还有其他client在，如果没有则调用停止推送流程
on_publish则是简单的判断推送流的来源合法性
on_publish_done则是调用停止推送流程

目前测试的是通过解码器压力测试，同时播放90路左右的流，并发高的情况下，可能会存在不停的调用on_play、on_play_done
