### ISSUE TITLE
能按需拉流吗？

### ISSUE THREAD

**Issue by xzzh999** [winshining/nginx-http-flv-module#58]
比如在web点播了流之后，服务器才去调用 ffmpeg 拉流，点播关闭之后，一段延时之后自动关闭掉这个流?

**Comment by winshining** [comment]
可以，用pull就行

**Comment by xzzh999** [comment]
@winshining 感谢，我试试看

**Comment by winshining** [comment]
是nginx-rtmp支持的，可以参考：https://github.com/arut/nginx-rtmp-module/wiki/Directives#pull
