### ISSUE TITLE
http-flv 可有配置关于直播flv的文档，您的博客和这里我翻了很久都没有翻到，烦请大神告知！

### ISSUE THREAD

**Issue by man201601** [winshining/nginx-http-flv-module#6]
不会配置播放flv，烦请大神告知，在nginx配置里！最好有相应实例！感谢！

**Comment by winshining** [comment]
工程里的README.CN.md里有专门说明

**Comment by winshining** [comment]
使用方法-例子

**Comment by man201601** [comment]
server {
        listen 8080; #不是默认的80端口
        ...

        location /live {
            flv_live on;
        }
    }这个例子里也只是说开启了一个端口，但是到底怎么加载flv，客户端如何调用 没有提

**Comment by man201601** [comment]
大神见谅，头一次研究 很多不懂，麻烦您了！

**Comment by winshining** [comment]
那个只是说明不使用默认端口（HTTP协议默认使用80端口）时怎么填写播放url，下面的location才是主要的，flv_live这个配置项是这个模块使用的。
至于加载flv，我不太清楚你是用来直播还是点播，点播的话，nginx不需要额外模块就支持flv点播，直播的话，需要先推流，用ffmpeg，然后用播放器播放（拉流），我调试的时候主要用VLC，OBS也试过，还有外国网友用MPV测试过。
推流之后，打开VLC，选择网络方式，填写url就可以播放了，这儿的url就跟你在浏览器里输入的url格式差不多，推流和播放说明文档里都有说明。
