### ISSUE TITLE
VLC多次拉取播放rtmp或http-flv流的问题

### ISSUE THREAD

**Issue by chinesezyc** [winshining/nginx-http-flv-module#62]
ffmpeg推送一段rtmp流时，VLC多次拉取播放rtmp或http-flv流时，只有第一次播放声音画面都有，后续播放只有声音没有画面，且延迟很大。
上述情况：
a.	使用Nginx-rtmp-module重复拉取rtmp流，不存在问题。
b.	使用Nginx-http-flv-module重复拉取rtmp或http-flv流，存在问题。

使用opencv读取rtmp流：
[NULL @ 00000000004ee480] sps_id 0 out of range
[NULL @ 00000000004ee480] sps_id 0 out of range
[NULL @ 00000000004ee480] Invalid NAL unit size (0 > 78576).
[NULL @ 00000000004ee480] missing picture in access unit with size 78576
[h264 @ 00000000004ee480] sps_id 0 out of range
[h264 @ 00000000004ee480] sps_id 0 out of range
[NULL @ 00000000004ee480] Invalid NAL unit size (0 > 4371).
[NULL @ 00000000004ee480] missing picture in access unit with size 4371
[NULL @ 00000000004ee480] Invalid NAL unit size (0 > 153).
[NULL @ 00000000004ee480] missing picture in access unit with size 153

出错代码在：FFmpeg/libavcodec/h2645_parse.h
static inline int get_nalsize(int nal_length_size, const uint8_t *buf,int buf_size, int *buf_index, void *logctx)
{
    int i, nalsize = 0;
    if (*buf_index >= buf_size - nal_length_size) {
        // the end of the buffer is reached, refill it
        return AVERROR(EAGAIN);
    }

    for (i = 0; i < nal_length_size; i++)
        nalsize = ((unsigned)nalsize << 8) | buf[(*buf_index)++];
    if (nalsize <= 0 || nalsize > buf_size - *buf_index) {
        av_log(logctx, AV_LOG_ERROR,
               "Invalid NAL unit size (%d > %d).\n", nalsize, buf_size - *buf_index);
        return AVERROR_INVALIDDATA;
    }
    return nalsize;
}
找不到解决思路，求助：）谢谢大神

**Comment by winshining** [comment]
既然找到问题了，那我就关闭这个issue了

**Comment by chinesezyc** [comment]
指定libx264、h264等解码视频流，问题消失
ffmpeg -re -i /home/zyc/X23.mp4 -vcodec libx264 -acodec copy -f flv rtmp://100.114.199.96:1935/live_app/live_stream
