### ISSUE TITLE
鉴权要怎么做？

### ISSUE THREAD

**Issue by toffstechzhang** [winshining/nginx-http-flv-module#63]
nginx-http-flv-module 1.2.4

同样的代码，nginx-rtmp-module工作正常，nginx-http-flv-module  不能工作。

`````

rtmp :
。。。。
    application toffs {
        live on;
        
        notify_method get;
        on_play http://127.0.0.1/on_play;
	}
。。。

http:
        location /on_play {
            secure_link $arg_key,$arg_time;
            secure_link_md5 "$auth_key$arg_name$arg_time $auth_key";

            if ($secure_link = "") {
                return 403;#验证失败
            }

            if ($secure_link = "0") {
                return 410;#验证成功，但时间失效
            }

            return 200;
        }

`````

error log:
.......
2018/08/30 21:22:03 [info] 12678#0: *2288 createStream, client: 220.255.95.55, server: 0.0.0.0:1935
2018/08/30 21:22:03 [info] 12678#0: *2288 play: name='test' args='key=ZPA7mTep7tz2Dj4yqNs9GA&time=1538300861' start=-2000 duration=0 reset=0 silent=0, client: 220.255.95.44, server: 0.0.0.0:1935
2018/08/30 21:22:03 [info] 12678#0: *2288 notify: play '127.0.0.1/on_play', client: 220.255.95.55, server: 0.0.0.0:1935
2018/08/30 21:22:03 [info] 12678#0: *2288 disconnect, client: 220.255.95.55, server: 0.0.0.0:1935
2018/08/30 21:22:03 [info] 12678#0: *2288 deleteStream, client: 220.255.95.55, server: 0.0.0.0:1935

**Comment by winshining** [comment]
用debug级别打印日志看看是什么问题

**Comment by toffstechzhang** [comment]
问是基本可确定$arg_name(流名）的值不会传入到，location /on_play 
现在我改为：

location /on_play {
            secure_link $arg_key,$arg_time;
            secure_link_md5 "$auth_key$arg_time $auth_key";
。。。。。。。。。。

在location /on_play，只有$arg_key,$arg_time;会正确传入。

**Comment by winshining** [comment]
下面的测试使用的播放链接都是：

    rtmp://10.0.11.93/myapp/mystream

按照你说的，我用下面的配置：

    location /on_play {
        if ($arg_name = 'mystream') {
            return 400;
        }

        return 200;
    }

打印日志如下：
2018/08/31 17:16:27 [debug] 24185#0: *8 http request line: "GET /on_play?app=myapp&flashver=LNX%209,0,124,2&swfurl=&tcurl=rtmp://10.0.11.93:1935/myapp&pageurl=&addr=10.1.21.14&clientid=6&call=play&name=mystream&start=4294965296&duration=0&reset=0 HTTP/1.0"
2018/08/31 17:16:27 [debug] 24185#0: *8 http uri: "/on_play"
2018/08/31 17:16:27 [debug] 24185#0: *8 http args: "app=myapp&flashver=LNX%209,0,124,2&swfurl=&tcurl=rtmp://10.0.11.93:1935/myapp&pageurl=&addr=10.1.21.14&clientid=6&call=play&name=mystream&start=4294965296&duration=0&reset=0"
2018/08/31 17:16:27 [debug] 24185#0: *8 http exten: ""
2018/08/31 17:16:27 [debug] 24185#0: *8 posix_memalign: 00000000009D06B0:4096 @16
2018/08/31 17:16:27 [debug] 24185#0: *8 http process request header line
2018/08/31 17:16:27 [debug] 24185#0: *8 http header: "Host: localhost"
2018/08/31 17:16:27 [debug] 24185#0: *8 http header: "Content-Type: application/x-www-form-urlencoded"
2018/08/31 17:16:27 [debug] 24185#0: *8 http header: "Connection: Close"
2018/08/31 17:16:27 [debug] 24185#0: *8 http header: "Content-Length: 0"
2018/08/31 17:16:27 [debug] 24185#0: *8 http header done
2018/08/31 17:16:27 [debug] 24185#0: *8 event timer del: 16: 8714136826
2018/08/31 17:16:27 [debug] 24185#0: *8 rewrite phase: 0
2018/08/31 17:16:27 [debug] 24185#0: *8 test location: "/"
2018/08/31 17:16:27 [debug] 24185#0: *8 test location: "on_play"
2018/08/31 17:16:27 [debug] 24185#0: *8 test location: ~ "\.php$"
2018/08/31 17:16:27 [debug] 24185#0: *8 using configuration "/on_play"
2018/08/31 17:16:27 [debug] 24185#0: *8 http cl:0 max:104857600
2018/08/31 17:16:27 [debug] 24185#0: *8 rewrite phase: 2
2018/08/31 17:16:27 [debug] 24185#0: *8 http script var
2018/08/31 17:16:27 [debug] 24185#0: *8 http script var: "mystream"
2018/08/31 17:16:27 [debug] 24185#0: *8 http script value: "mystream"
2018/08/31 17:16:27 [debug] 24185#0: *8 http script equal
2018/08/31 17:16:27 [debug] 24185#0: *8 http script if
2018/08/31 17:16:27 [debug] 24185#0: *8 http finalize request: 400, "/on_play?app=myapp&flashver=LNX%209,0,124,2&swfurl=&tcurl=rtmp://10.0.11.93:1935/myapp&pageurl=&addr=10.1.21.14&clientid=6&call=play&name=mystream&start=4294965296&duration=0&reset=0" a:1, c:1
2018/08/31 17:16:27 [debug] 24185#0: *8 http special response: 400, "/on_play?app=myapp&flashver=LNX%209,0,124,2&swfurl=&tcurl=rtmp://10.0.11.93:1935/myapp&pageurl=&addr=10.1.21.14&clientid=6&call=play&name=mystream&start=4294965296&duration=0&reset=0"
2018/08/31 17:16:27 [debug] 24185#0: *8 http set discard body
2018/08/31 17:16:27 [debug] 24185#0: *8 HTTP/1.1 400 Bad Request^M
Server: nginx/1.13.10^M
Date: Fri, 31 Aug 2018 09:16:27 GMT^M
Content-Type: text/html^M
Content-Length: 174^M
Connection: close^M

然后修改配置为：

    location /on_play {
        if ($arg_name = 'mystream') {
            return 200;
        }

        return 400;
    }

打印日志如下：
2018/08/31 17:18:12 [debug] 24292#0: *4 http request line: "GET /on_play?app=myapp&flashver=LNX%209,0,124,2&swfurl=&tcurl=rtmp://10.0.11.93:1935/myapp&pageurl=&addr=10.1.21.14&clientid=2&call=play&name=mystream&start=4294965296&duration=0&reset=0 HTTP/1.0"
2018/08/31 17:18:12 [debug] 24292#0: *4 http uri: "/on_play"
2018/08/31 17:18:12 [debug] 24292#0: *4 http args: "app=myapp&flashver=LNX%209,0,124,2&swfurl=&tcurl=rtmp://10.0.11.93:1935/myapp&pageurl=&addr=10.1.21.14&clientid=2&call=play&name=mystream&start=4294965296&duration=0&reset=0"
2018/08/31 17:18:12 [debug] 24292#0: *4 http exten: ""
2018/08/31 17:18:12 [debug] 24292#0: *4 posix_memalign: 0000000002417980:4096 @16
2018/08/31 17:18:12 [debug] 24292#0: *4 http process request header line
2018/08/31 17:18:12 [debug] 24292#0: *4 http header: "Host: localhost"
2018/08/31 17:18:12 [debug] 24292#0: *4 http header: "Content-Type: application/x-www-form-urlencoded"
2018/08/31 17:18:12 [debug] 24292#0: *4 http header: "Connection: Close"
2018/08/31 17:18:12 [debug] 24292#0: *4 http header: "Content-Length: 0"
2018/08/31 17:18:12 [debug] 24292#0: *4 http header done
2018/08/31 17:18:12 [debug] 24292#0: *4 event timer del: 16: 8714241878
2018/08/31 17:18:12 [debug] 24292#0: *4 rewrite phase: 0
2018/08/31 17:18:12 [debug] 24292#0: *4 test location: "/"
2018/08/31 17:18:12 [debug] 24292#0: *4 test location: "on_play"
2018/08/31 17:18:12 [debug] 24292#0: *4 test location: ~ "\.php$"
2018/08/31 17:18:12 [debug] 24292#0: *4 using configuration "/on_play"
2018/08/31 17:18:12 [debug] 24292#0: *4 http cl:0 max:104857600
2018/08/31 17:18:12 [debug] 24292#0: *4 rewrite phase: 2
2018/08/31 17:18:12 [debug] 24292#0: *4 http script var
2018/08/31 17:18:12 [debug] 24292#0: *4 http script var: "mystream"
2018/08/31 17:18:12 [debug] 24292#0: *4 http script value: "mystream"
2018/08/31 17:18:12 [debug] 24292#0: *4 http script equal
2018/08/31 17:18:12 [debug] 24292#0: *4 http script if
2018/08/31 17:18:12 [debug] 24292#0: *4 http set discard body
2018/08/31 17:18:12 [debug] 24292#0: *4 HTTP/1.1 200 OK^M
Server: nginx/1.13.10^M
Date: Fri, 31 Aug 2018 09:18:12 GMT^M
Content-Type: application/octet-stream^M
Content-Length: 0^M
Connection: close^M

并且从打印日志也可以看出是传递了name（流的名称）的，请确认你的配置正确。
