### ISSUE TITLE
请问直播延迟超过10秒以上是正常现象吗？

### ISSUE THREAD

**Issue by AngryTurf** [winshining/nginx-http-flv-module#67]
我使用的WSL，OS的版本是Ubuntu18.04。我的一台PC在局域网内进行推流，局域网内的另一台设备进行拉流，局域网使用的是千兆的无线路由器，但推流端使用的是网线连接方式，推流的视频质量比特率是10000，分辨率是1080P，60FPS。我使用任何工具拉流都会出现延迟，延迟多少不稳定，但至少会有10秒以上的延迟。我使用的是示例中的nginx配置，请问这是否与配置有关？应该怎么配置能减少延迟？另外是不是有可能和我使用的是WSL有关？另外关于视频质量我试过使用更低质量的视频，但是延迟并没有任何减少。

**Comment by winshining** [comment]
不太好确定。你先看看你发布的流的GOP是多少，如果GOP（我见过8秒的GOP）比较大，并且开启了gop_cache选项，那么延迟就会比较大，另外，有些播放器会缓存一些数据后再播放，而不是拿到I帧后就播放，我测试过从阿里云的服务器上拉香港卫视的流，然后用nginx-http-flv-module自带的JW Player播放，对比用VLC直接播香港卫视的流，前者居然比后者还快一小点！

**Comment by AngryTurf** [comment]
非常感谢，刚才去看了一下OBS的推流，关键帧间隔居然设置成了5秒… 
我的播放器是ijkplayer，播放速度和VLC基本相同，只是播放一段时间(3分钟左右)后会增加一些延迟，与VLC比较大概是增加了3秒以上。
