### ISSUE TITLE
建议在说明中加入nginx版本要求

### ISSUE THREAD

**Issue by zhouweitong3** [winshining/nginx-http-flv-module#7]
nginx-http-flv-module要求nginx版本在1.11.1以上，用低版本的nginx或者其他基于低版本的nginx的衍生版（譬如tengine）编译时会出现错误。个人觉得应该在readme里面注明一下。

**Comment by winshining** [comment]
本来就没考虑兼容ngin其他的衍生版本的，一直用nginx-1.11.10做测试，wiki里写了点版本要求，主要是为了支持动态加载模块的最低版本，nginx-1.9.11。

**Comment by zhouweitong3** [comment]
Thanks for taking it into consideration.

**Comment by winshining** [comment]
今天上午把目前已发现的兼容问题改好了，目前只测试到nginx-1.8.1，没再往更旧的版本测试，谢谢提出这个问题 @zhouweitong3
