### ISSUE TITLE
[bug] auth_request fails

### ISSUE THREAD

**Issue by invalidtask** [winshining/nginx-http-flv-module#72]
When attempting to use auth_request to authenticate connections, the auth request will fail with the following error:

2018/09/24 20:01:57 [emerg] 139#139: io_setup() failed (38: Function not implemented)

### Expected behavior
Depending on the response code of the auth_request, it should either allow the connection or reject it

### Actual behavior
In browser the connection hangs, in the error log it reports failed

### Steps to reproduce the behavior 

Snippet from config:

        location /live {
            flv_live on; #open flv live streaming (subscribe)
            chunked_transfer_encoding  off; #open 'Transfer-Encoding: chunked' response
            auth_request /auth_flv ;
        }
        location /auth_flv {
            proxy_pass https://url_to_auth.php;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header X-Original-URI $request_uri;
        }

In browser, go to http://server_ip/live?app=live&stream=some_stream_name

If auth_request works, the stream will load/play. If it fails, the request will hang.

**Comment by winshining** [comment]
The bug is fixed, try the latest code.
Thank you for posting the issue.
Good luck!

**Comment by invalidtask** [comment]
Thank you so much! You are greatly appreciated!
