### ISSUE TITLE
http和rtmp同时开启产生core

### ISSUE THREAD

**Issue by han4235** [winshining/nginx-http-flv-module#76]
你好：
    当我将nginx的 http 代理开启，同时也开启rtmp模块的情况下， 发现会频繁的产生core，
#0  ngx_get_connection (s=261, log=0x2c6c480) at src/core/ngx_connection.c:1078
1078    src/core/ngx_connection.c: No such file or directory.
        in src/core/ngx_connection.c
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.80.el6.x86_64 libgcc-4.4.7-17.el6.x86_64 nss-softokn-freebl-3.12.9-11.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt
#0  ngx_get_connection (s=261, log=0x2c6c480) at src/core/ngx_connection.c:1078
#1  0x000000000047a50b in ngx_event_accept (ev=0xcf32a50) at src/event/ngx_event_accept.c:144
#2  0x0000000000485151 in ngx_epoll_process_events (cycle=0x2c68460, timer=<value optimized out>, flags=<value optimized out>) at src/event/modules/ngx_epoll_module.c:900
#3  0x0000000000479419 in ngx_process_events_and_timers (cycle=0x2c68460) at src/event/ngx_event.c:252
#4  0x0000000000481e35 in ngx_worker_process_cycle (cycle=0x2c68460, data=<value optimized out>) at src/os/unix/ngx_process_cycle.c:821
#5  0x00000000004801c4 in ngx_spawn_process (cycle=0x2c68460, proc=0x481df0 <ngx_worker_process_cycle>, data=0x6, name=0x7b477b "worker process", respawn=-4) at src/os/unix/ngx_process.c:198
#6  0x00000000004825ea in ngx_start_worker_processes (cycle=0x2c68460, n=8, type=-4) at src/os/unix/ngx_process_cycle.c:398
#7  0x0000000000483226 in ngx_master_process_cycle (cycle=0x2c68460) at src/os/unix/ngx_process_cycle.c:250
#8  0x000000000045802c in main (argc=<value optimized out>, argv=<value optimized out>) at src/core/nginx.c:367

报错的位置很奇怪， 貌似是两者在连接池上处理得冲突了， 不知道其他人有遇到过类似的情况没有， 我最近也会测试下arut的rtmp模块看看， 是否也会出现类似的问题

**Comment by winshining** [comment]
迄今为止，除了你以外没收到过崩溃在这里的bug反馈。
QQ上交流你说用的OpenResty，建议先用Nginx测试，将这个不同的因素排除掉，如果还有问题，再反馈给我。
