### ISSUE TITLE
[ bug ] Slow response time

### ISSUE THREAD

**Issue by invalidtask** [winshining/nginx-http-flv-module#77]
~~Edit: After observing resource usage of each worker, this may be caused by workers reaching 100% CPU usage. Much apologies for opening this issue without fully investigating. I am closing this issue.~~

Edit 2: Experiencing this issue contrary to my previous edit message. Happening at 20% CPU and roughly 600 clients. 

Edit 3: I'm running an instance in debug mode, this seems to show up whenever there is a slow response time:

`accept() not ready (11: Resource temporarily unavailable)`

Edit 4: I have no idea if any of this info is relevant, my apologies if its not:

> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: abs audio header timestamp=31357738
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 flv live: HTTP drop message bufs='4096', priority='0'
> 2018/10/12 14:40:30 [debug] 25216#25216: *1284 SSL_write: 128
> 2018/10/12 14:40:30 [debug] 25216#25216: *1284 SSL to write: 128
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: abs audio header timestamp=31357760
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 flv live: HTTP drop message bufs='4096', priority='0'
> 2018/10/12 14:40:30 [debug] 25216#25216: *1284 SSL_write: 128
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: skip non-key
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: abs audio header timestamp=31357781
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 flv live: HTTP drop message bufs='4096', priority='0'
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: skip non-key
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: abs audio header timestamp=31357802
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 flv live: HTTP drop message bufs='4096', priority='0'
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: abs audio header timestamp=31357824
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 flv live: HTTP drop message bufs='4096', priority='0'
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: skip non-key
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: abs audio header timestamp=31357845
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 flv live: HTTP drop message bufs='4096', priority='0'
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: abs audio header timestamp=31357866
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 flv live: HTTP drop message bufs='4096', priority='0'
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: skip non-key
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: abs audio header timestamp=31357888
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 flv live: HTTP drop message bufs='4096', priority='0'
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: skip non-key
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: abs audio header timestamp=31357909
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 flv live: HTTP drop message bufs='4096', priority='0'
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: abs audio header timestamp=31357930
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 flv live: HTTP drop message bufs='4096', priority='0'
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: skip non-key
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: abs audio header timestamp=31357952
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 flv live: HTTP drop message bufs='4096', priority='0'
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: skip non-key
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: abs audio header timestamp=31357973
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 flv live: HTTP drop message bufs='4096', priority='0'
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: abs audio header timestamp=31357994
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 flv live: HTTP drop message bufs='4096', priority='0'
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: skip non-key
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: abs audio header timestamp=31358016
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 flv live: HTTP drop message bufs='4096', priority='0'
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: skip non-key
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: abs audio header timestamp=31358037
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 flv live: HTTP drop message bufs='4096', priority='0'
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: abs audio header timestamp=31358058
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 flv live: HTTP drop message bufs='4096', priority='0'
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: skip non-key
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: abs audio header timestamp=31358080
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 flv live: HTTP drop message bufs='4096', priority='0'
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: abs audio header timestamp=31358101
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 flv live: HTTP drop message bufs='4096', priority='0'
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: skip non-key
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: abs audio header timestamp=31358122
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 flv live: HTTP drop message bufs='4096', priority='0'
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: skip non-key
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: abs audio header timestamp=31358144
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 flv live: HTTP drop message bufs='4096', priority='0'
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: abs audio header timestamp=31358165
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 flv live: HTTP drop message bufs='4096', priority='0'
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: skip non-key
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: abs audio header timestamp=31358186
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 flv live: HTTP drop message bufs='4096', priority='0'
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: skip non-key
> 2018/10/12 14:39:58 [debug] 25222#25222: *1227 live: abs audio header timestamp=31358208

### Expected behavior
HTTP request to be returned quickly

### Actual behavior
It seems there are client connections blocking/slowing down new requests. Specifically noticeable if a client is dropping a lot of frames (per the stat page under stream name). As a result, HTTP requests (as well as plain text HTTP) can take up to 15 seconds to respond and load. This doesn't happen across all processes, seems to only happen on processes with playback clients that drop a lot of frames.

### Steps to reproduce the behavior 
I don't know how to replicate a client with a bad connection :(

Configuration file:
```
user root;
worker_processes 16;
worker_cpu_affinity auto;
pid /run/nginx.pid;
worker_rlimit_nofile 1048576;

events {
    worker_connections 1048576;
    multi_accept on;
    use epoll;
    accept_mutex on;
}
http {
    include mime.types;
    default_type application/octet-stream;
    keepalive_timeout 3;
    access_log off;
    error_log off;
    sendfile on;
    server_tokens off;
    gzip on;
    server {
        listen 80;
        location / {
            root /var/html/www;
            index index.html;
        }
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root html;
        }
        location /live {
            flv_live on; #open flv live streaming (subscribe)
            chunked_transfer_encoding off; #open 'Transfer-Encoding: chunked' response
        }
    }
}

rtmp_auto_push on;
rtmp_auto_push_reconnect 1s;
rtmp_socket_dir /tmp;

rtmp {
    out_queue   4096;
    out_cork    8;
    max_streams 10240;
    access_log  off;
    server {
        listen 1935;
        application live {
            live on;
            deny publish all;
            gop_cache off; #open GOP cache for low latency
            pull rtmp://localhost/live;
        }
    }
}
```

**Comment by winshining** [comment]
No publisher but only used as a edge server?

The command:

    pull rtmp://localhost/live;

will pull recursively from localhost!

It's better to set the directive `worker_processes` as 1 and comment out the directive `worker_cpu_affinity`, because there is still some bugs as muliti-processes mode enabled in finding the correct application when `connect` command is received.

I tested the module and CPU usage was about 25%, slow response happened very randomly but I have no idea what caused that yet.

**Comment by invalidtask** [comment]
In production the pull it points to a Wowza instance that runs on same machine. I wasn't aware of the localhost issue. 

I need many workers because I have tens thousands viewers and one worker cannot handle that many. I not try many single worker instance yet but can do so. But still the random slowness makes nearly unusable :( 

Please do not mistake, I am very appreciative of your work and hope to help make it better for all.

**Comment by HeyJupiter** [comment]
@winshining So how to reproduce the bug as "muliti-processes mode enabled in finding the correct application when connect `command` is received"? I've been testing the module always with the directive `woker_processes auto` enabled (nginx-1.13.10 & the latest nginx-http-flv-module) but it has been working perfectly for me.
Looking forward to your reply cause I nearly used it in product environment.

**Comment by winshining** [comment]
@invalidtask @HeyJupiter It's easy to reproduce the bug. Assuming that you have 2 `server` blocks in the `rtmp` block and there are 2 different values of directive `listen` (1935 by default and 1985, for example) in the 2 `server` blocks. Subscription to the second one **MAY** fail if the publisher and the subscriber comes from the different processes. The reason is that the AUTO PUSH works on the base of **Unix Domain Socket**, it has no port information (the **Unix Domain Socket** is only a file, located in /tmp and named as nginx-rtmp.X by default). So the parameter `port` in the URL of a HTTP request can not be used to find the correct `server` block.
But if you have only one `server` block in the `rtmp` block, it works as expected.
I've attempted to fix it many times but haven't worked it out yet. I need help.

**Comment by HeyJupiter** [comment]
@winshining Yes, I have only one server block in rtmp block but I may need more in the future.  It's too hard for me to hack the C code. I can hardly provide help, god blesses you!

**Comment by invalidtask** [comment]
I am of curious if any progress has been made on this issue

**Comment by winshining** [comment]
@invalidtask Well, the debug log you provided:

    flv live: HTTP drop message bufs='4096', priority='0'

means that your network condition was not very well or your clients (maybe players) didn't receive data from the server, it **may be** the reason?

**Comment by invalidtask** [comment]
I isolated the server and ensure it has sufficient network bandwidth and same result. But I am using SSL, could this be the issue? I compiled nginx and this module and openssl and delivering flv streams via HTTPS instead of HTTP

**Comment by winshining** [comment]
Have you ever used [Wireshark](https://www.wireshark.org/download.html) to capture network data? You can analyze the time when packages sent to server from clients and sent to clients by server.
BTW, SSL doesn't matter, which is handled not by nginx-http-flv-module but Nginx.

**Comment by invalidtask** [comment]
Wireshark yes, but on Windows not on Linux. Could one user with a bad connection cause the nginx process to hang resulting in the slow loading for all incoming connections? This doesn't happen on nginx by itself, only with this module.

**Comment by winshining** [comment]
Well, please post the analytical statistics of wireshark. I rarely use Windows.
As I've mentioned: 

    flv live: HTTP drop message bufs='4096', priority='0'

meant that your clients didn't receive data but server tried to send until timeout (so it meant the server didn't hang), I think that is the issue you should pay attention to.
