### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by xujin51** [winshining/nginx-http-flv-module#8]
之前安装过nginx-rtmp-module已经正常运行，现在编译nginx安装nginx-rtmp-module和nginx-http-flv-module出现这个错误，是那里出了问题？（还是只需安装nginx-http-flv-module 不用安装ginx-rtmp-module）

objs/Makefile:1916: recipe for target 'objs/addon/hls/ngx_rtmp_hls_module.o' failed
make[1]: *** [objs/addon/hls/ngx_rtmp_hls_module.o] Error 1
make[1]: Leaving directory '/src/nginx-1.12.1'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by winshining** [comment]
不用安装nginx-rtmp-module，这个模块就是在nginx-rtmp-module的基础上修改的，nginx-rtmp-module的功能都有，不过没有完整测试过。
刚刚用nginx-1.12.1试过，在服务器上编译过了，检查一下你的Makefile的编码是不是有问题。

**Comment by xujin51** [comment]
好的大栳，安装上了
