### ISSUE TITLE
打开多个播放器播放同一直播时，nginx会把之前的已经打开的播放连接关闭

### ISSUE THREAD

**Issue by gaoxianrui52** [winshining/nginx-http-flv-module#81]
### nginx配置如下

> events {
>     worker_connections 1048576;
>     multi_accept on;
>     use epoll;
>     accept_mutex on;
> }
> http {
>         error_log  logs/error.log debug;
>         include mime.types;
>         default_type application/octet-stream;
>         keepalive_timeout 65;
>         server {
>         listen 80;
>         location / {
>                 root /var/www;
>                 index index.html index.htm;
>         }
>         error_page 500 502 503 504 /50x.html;
>         location = /50x.html {
>                 root html;
>         }
>         location /live {
>                 flv_live on;
>                 #chunked_transfer_encoding  on; #open 'Transfer-Encoding: chunked' response
>                 add_header 'Access-Control-Allow-Origin' '*'; #add additional HTTP header
>                 add_header 'Access-Control-Allow-Credentials' 'true'; #add additional HTTP header
>                 }
>         }
> }
> rtmp_auto_push on;
> rtmp_auto_push_reconnect 10s;
> rtmp_socket_dir /tmp;
> rtmp {
>         drop_idle_publisher 15s;
>         out_queue 40960;
>         out_cork 64;
>         max_streams 102400;
>         server {
>                 listen 1935;
>                 drop_idle_publisher 15s;
>                 application myapp {
>                         drop_idle_publisher 15s;
>                         live on;
>                         gop_cache on;
>                         #pull rtmp://live.hkstv.hk.lxdns.com/live/hks;
>                         pull rtmp://xxx.xxx.xxx.xxx/xx;  ###我自己的rtmp源
>                 }
>         }
> }

使用potplayer播放器时，同一局域网内超过2个客户端播放都会挤掉前面打开的客户端。potplayer直接使用rtmp方式播放是正常的。使用VLC播放器http及rtmp都正常，百思不得其解。
请教一下。

另外贴一下日志：

> 2018/11/15 06:12:20 [info] 2054#0: *53 flv live: name='jd10701' args='app=myapp&stream=jd10701' start=0 duration=0 reset=0 silent=0, client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:20 [info] 2054#0: *53 relay: create pull name='jd10701' app='' playpath='' url='xxx', client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:20 [warn] 2054#0: *53 flv live: chunked only supported by HTTP/1.1, client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:20 [info] 2054#0: *53 send() failed (104: Connection reset by peer), client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:20 [info] 2054#0: *53 disconnect, client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:20 [info] 2054#0: *53 deleteStream, client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:20 [info] 2054#0: *54 flv live: *54 client connected '192.168.102.38', client: 192.168.102.38, server: , request: "GET /live?app=myapp&stream=jd10701 HTTP/1.0", host: "192.168.102.194:80"
> 2018/11/15 06:12:20 [info] 2054#0: *54 flv live: name='jd10701' args='app=myapp&stream=jd10701' start=0 duration=0 reset=0 silent=0, client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:20 [info] 2054#0: *54 relay: create pull name='jd10701' app='' playpath='' url='xxx', client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:20 [warn] 2054#0: *54 flv live: chunked only supported by HTTP/1.1, client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:20 [info] 2054#0: *55 flv live: *55 client connected '192.168.102.38', client: 192.168.102.38, server: , request: "GET /live?app=myapp&stream=jd10701 HTTP/1.1", host: "192.168.102.194"
> 2018/11/15 06:12:20 [info] 2054#0: *55 flv live: name='jd10701' args='app=myapp&stream=jd10701' start=0 duration=0 reset=0 silent=0, client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:20 [info] 2054#0: *55 relay: create pull name='jd10701' app='' playpath='' url='xxx', client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:20 [info] 2054#0: *55 send() failed (32: Broken pipe), client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:20 [info] 2054#0: *55 disconnect, client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:20 [info] 2054#0: *55 deleteStream, client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:20 [info] 2054#0: *56 flv live: *56 client connected '192.168.102.38', client: 192.168.102.38, server: , request: "GET /live?app=myapp&stream=jd10701 HTTP/1.1", host: "192.168.102.194"
> 2018/11/15 06:12:20 [info] 2054#0: *56 flv live: name='jd10701' args='app=myapp&stream=jd10701' start=0 duration=0 reset=0 silent=0, client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:20 [info] 2054#0: *56 relay: create pull name='jd10701' app='' playpath='' url='xxx', client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:20 [info] 2054#0: *56 send() failed (32: Broken pipe), client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:20 [info] 2054#0: *56 disconnect, client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:20 [info] 2054#0: *56 deleteStream, client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:20 [info] 2054#0: *57 flv live: *57 client connected '192.168.102.38', client: 192.168.102.38, server: , request: "GET /live?app=myapp&stream=jd10701 HTTP/1.1", host: "192.168.102.194"
> 2018/11/15 06:12:20 [info] 2054#0: *57 flv live: name='jd10701' args='app=myapp&stream=jd10701' start=0 duration=0 reset=0 silent=0, client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:20 [info] 2054#0: *57 relay: create pull name='jd10701' app='' playpath='' url='xxx', client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:20 [info] 2054#0: *57 send() failed (32: Broken pipe), client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:20 [info] 2054#0: *57 disconnect, client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:20 [info] 2054#0: *57 deleteStream, client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:20 [info] 2054#0: *58 flv live: *58 client connected '192.168.102.38', client: 192.168.102.38, server: , request: "GET /live?app=myapp&stream=jd10701 HTTP/1.1", host: "192.168.102.194"
> 2018/11/15 06:12:20 [info] 2054#0: *58 flv live: name='jd10701' args='app=myapp&stream=jd10701' start=0 duration=0 reset=0 silent=0, client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:20 [info] 2054#0: *58 relay: create pull name='jd10701' app='' playpath='' url='xxx', client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:22 [info] 2054#0: *54 recv() failed (104: Connection reset by peer), client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:22 [info] 2054#0: *54 send() failed (32: Broken pipe), client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:22 [info] 2054#0: *54 disconnect, client: 192.168.102.38, server: 0.0.0.0:1935
> 2018/11/15 06:12:22 [info] 2054#0: *54 deleteStream, client: 192.168.102.38, server: 0.0.0.0:1935

**Comment by winshining** [comment]
按照你的配置，pull使用rtmp://202.69.69.180:443/webcast/bshdlive-pc，一个用flv.js，一个用vlc，测试截图如下：
<img width="1243" alt="1" src="https://user-images.githubusercontent.com/3250905/48596498-39442900-e994-11e8-86dd-f9438602eabe.png">
我不清楚为什么播放器发送了请求后就关闭连接了，导致服务器发送数据失败(104: Connection reset by peer)！

**Comment by gaoxianrui52** [comment]
困惑的是用vlc播放打开多个都没问题，potplayer就异常停止

**Comment by gaoxianrui52** [comment]
用了wait_key on; 这个参数是可以的了。

**Comment by winshining** [comment]
那就是播放器处理不完美了
