### ISSUE TITLE
是否可以跨网直播？

### ISSUE THREAD

**Issue by yxw0823** [winshining/nginx-http-flv-module#83]
我使用nginx-http-flv-module在互联网搭建一套直播服务器已经能正常使用，现阶段想通过光闸把直播产生的文件同步到内网相同的直播服务器中，然后在企业内网查看视频。请问这个技术上可行吗? 或者有其他的方法可以实现这中跨网直播的需求？还请赐教！！！

**Comment by winshining** [comment]
广域网到局域网？

**Comment by yxw0823** [comment]
是的

**Comment by winshining** [comment]
从局域网推流到广域网的主机，从局域网的播放器向广域网主机发起播放请求都没有问题。
