### ISSUE TITLE
播放flv时,播放客户端的on_update事件导致nginx work死掉

### ISSUE THREAD

**Issue by asAngus** [winshining/nginx-http-flv-module#85]
When you meet a bug, please open the issue including a title prefixed by '[bug]' and describe it as follows:

### Expected behavior
播放flv时,播放客户端的on_update事件导致nginx work死掉

### Actual behavior
2019/01/25 22:47:13 [alert] 22596#0: worker process 22747 exited on signal 11   线程退出.

**Comment by asAngus** [comment]
nginx.conf配置如下:
rtmp {
    out_queue   4096;
    out_cork    8;
    max_streams 128;
    #timeout     15s;
    server {
        listen 1935;
        application live {
            live on;
            publish_notify on;
            on_publish http://127.0.0.1:8880/signaling/rtmp/on_publish;
            on_play http://127.0.0.1:8880/signaling/rtmp/on_play;
            on_play_done http://127.0.0.1:8880/signaling/rtmp/on_play_done;
            on_publish_done http://127.0.0.1:8880/signaling/rtmp/on_publish_done;

            on_update http://127.0.0.1:8880/signaling/rtmp/on_update;
            gop_cache on; #open GOP cache for reducing the wating time for the first picture of video
        }

        application hls {
            live on;
            hls on;
            hls_path /usr/local/nginx-http-flv-14/html/hls;
        }

        application dash {
            live on;
            dash on;
            dash_path /usr/local/nginx-http-flv-14/html/dash;
        }
    }

}

**Comment by asAngus** [comment]
@winshining  使用rtmp 进行播放没有问题,事件能通知,用flv播放就出错了.整个推流和播放都断了. 麻烦帮忙看下.非常感谢

**Comment by winshining** [comment]
请确认是哪个指令造成的崩溃，如何复现的？我用on_update返回200时，一切正常，返回非200（例如400）时，会断开推流和播放连接，但是进程没有崩溃。

**Comment by winshining** [comment]
还是无法复现，为了加大复现概率，我还用了压力测试，推200路，拉500路，将要执行的脚本移除以返回404等手段，还使用nginx-1.15.2测试。
你用gdb调试着运行吧，挂了看下堆栈信息，定位一下问题。

**Comment by winshining** [comment]
@asAngus 是每次都在同一个地方崩溃吗？贴一下堆栈信息我看看能不能找到问题

**Comment by winshining** [comment]
@asAngus 你是用master分支测试的吗？我在Linux和Mac上都测试过，确实复现不出来。昨晚用vhost分支测试倒是会崩溃，不知道你是不是用的这个分支？vhost分支还在修改，并不稳定。

**Comment by asAngus** [comment]
@winshining 您好,  我用的master分支.每次都是这个地方崩溃.

**Comment by asAngus** [comment]
每次在会触发on_update事件时死掉.

**Comment by winshining** [comment]
能贴一下崩溃的时候的堆栈信息吗？

**Comment by winshining** [comment]
问题复现出来了，不是on_update导致了，是on_XXX_done导致的，空了我看看问题

**Comment by winshining** [comment]
@asAngus 代码更新了，你测试一下，应该没问题了。测试完了请回复我一下，我好关闭issue，谢谢！

**Comment by asAngus** [comment]
不好意思,我这边春节的时候没有弄.多谢了.我测试下.
非常感谢.

**Comment by agustik** [comment]
Is this fixed?

I got the same issue on 1.2.11, the servers returns 200 and then I get a error on my RTMP streamer that the server disconnected.
