### ISSUE TITLE
exec_pull不能正确执行带有“\”字符ffmpeg命令行。

### ISSUE THREAD

**Issue by liangtaikonaut** [winshining/nginx-http-flv-module#87]
When you meet a bug, please open the issue including a title prefixed by '[bug]' and describe it as follows:

### Expected behavior
exec_pull正确执行带有“\”字符ffmpeg命令行。
### Actual behavior
"\"字符被吃掉，导致ffmpeg命令行无法正确执行。
### Steps to reproduce the behavior 

nginx.conf文件：
application emergency {
      live on;
      gop_cache on;
      exec_pull /root/bin/ffmpeg -re -stream_loop -1 -i /root/media/3.mp4 -re -stream_loop -1 -i /root/media/20190214162053_CN.wav -map 0:v -map 1:a -vf pad=640:400:0:0:darkblue,drawtext="fontfile=/usr/share/fonts/simsun.ttc:textfile=/root/media/20190214162053_CN.txt:shadowx=2:shadowy=2:shadowcolor=black:fontcolor=red:fontsize=36:y=H-lh-3:x=W-200-W/5*mod(t\\,floor(tw/(w/5)))" -vcodec libx264 -acodec aac -f flv rtmp://localhost:1935/emergency/program001;
    }

实际运行的命令行是：
/root/bin/ffmpeg -re -stream_loop -1 -i /root/media/3.mp4 -re -stream_loop -1 -i /root/media/20190214162053_CN.wav -map 0:v -map 1:a -vf pad=640:400:0:0:darkblue,drawtext="fontfile=/usr/share/fonts/simsun.ttc:textfile=/root/media/20190214162053_CN.txt:shadowx=2:shadowy=2:shadowcolor=black:fontcolor=red:fontsize=36:y=H-lh-3:x=W-200-W/5*mod(t,floor(tw/(w/5)))" -vcodec libx264 -acodec aac -f flv rtmp://localhost:1935/emergency/program001

注：mod函数中，”t“后面少了”\“

**Comment by winshining** [comment]
把"t\"改成"t\\\\"就可以了，按照这样修改后，测试验证传递给ffmpeg的参数是正确的：

    (gdb) p out->data
    $5 = (u_char *) 0x1850320 "pad=768:320:0:0:darkblue,drawtext=\"fontfile=/usr/share/fonts/truetype/wqy/wqy-zenhei.tcc:text=hellohellohello:shadowx=2:shadowy=2:shadowcolor=black:fontcolor=red:fontsize=36:y=H-lh-3:x=W-200-W/5*mod(t"...
    (gdb) p out->data + 20
    $7 = (u_char *) 0x1850334 "blue,drawtext=\"fontfile=/usr/share/fonts/truetype/wqy/wqy-zenhei.tcc:text=hellohellohello:shadowx=2:shadowy=2:shadowcolor=black:fontcolor=red:fontsize=36:y=H-lh-3:x=W-200-W/5*mod(t\\,floor(tw/(w/5)))\""

复制调试的参数到shell中可以正常运行（去掉两个双引号前的\和t\\的一个\，双引号在C语言中表示为\"，就跟反斜杠在C语言中表示为\\一样），但是execvp调用ffmpeg无法执行，很简单的ffmpeg命令调用execvp执行是可以的，只能解释为通过execvp调用时，ffmpeg无法解释很复杂的参数

**Comment by liangtaikonaut** [comment]
Winshining，
多谢解惑！

后来把下列参数
pad=640:400:0:0:darkblue,drawtext="fontfile=/usr/share/fonts/simsun.ttc:textfile=/root/media/20190214162053_CN.txt:shadowx=2:shadowy=2:shadowcolor=black:fontcolor=red:fontsize=36:y=H-lh-3:x=W-200-W/5*mod(t\\,floor(tw/(w/5)))" 
写入脚本文件lt-pad-roll.flg，nginx.conf配置改为：
exec_pull /root/bin/ffmpeg -re -stream_loop -1 -i /root/media/3.mp4 -re -stream_loop -1 -i /root/media/20190214162053_CN.wav -map 0:v -map 1:a -filter_complex_script /root/media/lt-pad-roll.flg -vcodec libx264 -acodec aac -f flv rtmp://localhost:1935/emergency/program001；
之后能够正常运行。
看来是nginx解析参数时，出了问题。
