### ISSUE TITLE
hls播放事件问题

### ISSUE THREAD

**Issue by asAngus** [winshining/nginx-http-flv-module#88]
@winshining  您好,麻烦请问下.我在播放hls的时候,是否能接收到rtmp里面的on_play, on_play_done, on_update等事件呢?

**Comment by winshining** [comment]
播放HLS的HTTP请求是短连接并且不会被转移到RTMP模块中处理，所以不支持on_xxx事件，除非你自己添加feature支持。

**Comment by asAngus** [comment]
好的.多谢.
