### ISSUE TITLE
exec_pull HLS请求触发请教以及多次请求的时候重复执行

### ISSUE THREAD

**Issue by WayChan** [winshining/nginx-http-flv-module#96]
When you meet a bug, please open the issue including a title prefixed by '[bug]' and describe it as follows:

### Expected behavior
二次请求的时候，当流存在，不重复触发exec_pull。
同时访问HLS的时候，流不能存在，触发exec_pull获取流来切片
### Actual behavior
二次请求的时候，当流存在，会触发exec_pull当中的命令，
访问HLS的时候，流不能存在，无法触发exec_pull获取流来切片，直接响应404

### Steps to reproduce the behavior 
nginx 主要配置文件
application live {
    live on;
    gop_cache on;

    exec_options on;
    exec_pull ffmpeg -re -i test.flv -codec copy -f flv rtmp://www.test.com/live/$name name=fffftest;

    hls on;
    wait_key on;
    hls_fragment 2;
    hls_playlist_length 6;
    hls_fragment_naming timestamp;
    hls_fragment_slicing aligned;
    hls_path /tmp/hls;
    hls_continuous on;
    hls_cleanup on;
    hls_nested on;
  }

**Comment by winshining** [comment]
1.播放的时候可以存在多个同名的流，每个请求都会触发exec_pull，这个逻辑没问题。只有推流的时候不允许存在多个同名的流。
2.HLS用的是HTTP协议，请求连接不会被转到RTMP模块来，所以无法触发exec_pull。HTTP-FLV用的也是HTTP协议，它为什么被转到RTMP模块来是本模块实现的功能之一。
